import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Theme = 'light' | 'dark';
type Language = 'en' | 'fr' | 'es' | 'ru' | 'zh' | 'ja' | 'de' | 'it' | 'pt' | 'sq';

interface AppContextType {
  theme: Theme;
  language: Language;
  toggleTheme: () => void;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const AppContext = createContext<AppContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.about': 'About',
    'nav.work': 'Work',
    'nav.services': 'Services',
    'nav.contact': 'Contact',
    'nav.letsTalk': 'Let\'s Talk',

    // Hero Section
    'hero.subtitle': 'Creative Solutions',
    'hero.greeting': 'Yo, I\'m Theo Blondel.',
    'hero.title1': 'Creative',
    'hero.title2': 'Solutions',
    'hero.description': 'I\'m a mediamatician in Switzerland, and I transform your ideas into clean, impactful, and really stylish visual projects.',
    'hero.contactMe': 'Let\'s talk?',
    'hero.watchDemo': 'Watch Demo',
    'hero.yearsExperience': 'Years Experience',
    'hero.projectsDelivered': 'Projects Delivered',
    'hero.clientSatisfaction': 'Client Satisfaction',
    'hero.clientsWorldwide': 'Clients Worldwide',
    'hero.service1.title': 'Brand Identity',
    'hero.service1.desc': 'Professional logos and visual identity',
    'hero.service2.title': 'UI/UX Design',
    'hero.service2.desc': 'Intuitive and engaging interfaces',
    'hero.service3.title': 'Motion Graphics',
    'hero.service3.desc': 'Dynamic animations and videos',
    'hero.service4.title': 'Print Design',
    'hero.service4.desc': 'Professional print materials',

    // About Section
    'about.subtitle': 'My Journey',
    'about.title1': 'Creative at heart,',
    'about.title2': 'efficient in form.',
    'about.description1': 'I started like many: with YouTube montages at 15, head in pixels and sound effects. Minecraft, Fortnite, Call of... I spent hours testing, tinkering, looking for what works.',
    'about.description2': 'Then drawing came. Then mediamatique. And there, I got it: I want to do this. Create. Design. Bring visual ideas to life that speak to people.',
    'about.skill1.title': 'Adobe Creative Suite',
    'about.skill1.desc': 'Professional mastery of the complete suite',
    'about.skill2.title': 'DaVinci Resolve',
    'about.skill2.desc': 'Advanced video editing and color grading',
    'about.skill3.title': 'Autodesk Suite',
    'about.skill3.desc': '3D modeling and animation',
    'about.skill4.title': 'Figma',
    'about.skill4.desc': 'UI/UX design and prototyping',

    // Portfolio Section
    'portfolio.subtitle': 'My Projects',
    'portfolio.title1': 'Some stuff',
    'portfolio.title2': 'I loved doing',
    'portfolio.description': 'A selection of projects that showcase my creative approach and technical expertise.',
    'portfolio.category.all': 'All',
    'portfolio.category.webApp': 'Web App',
    'portfolio.category.branding': 'Branding',
    'portfolio.category.mobile': 'Mobile',
    'portfolio.category.animation': 'Animation',
    'portfolio.category.audio': 'Audio',
    'portfolio.viewAllBehance': 'View all on Behance',

    // Services Section
    'services.subtitle': 'What I Can Do',
    'services.title': 'What I can do for you',
    'services.description': 'Complete creative solutions tailored to your needs and goals.',
    'services.brandIdentity.title': 'Brand Identity',
    'services.brandIdentity.desc': 'Need a logo that rocks and an image that tells who you are? I help you build a real identity — not just a quick logo.',
    'services.brandIdentity.feature1': 'Professional Logo (not on Canva)',
    'services.brandIdentity.feature2': 'Clear brand guidelines',
    'services.brandIdentity.feature3': 'Coherent visual identity',
    'services.brandIdentity.feature4': 'Solid brand positioning',
    'services.uiux.title': 'UI/UX Design',
    'services.uiux.desc': 'Good design isn\'t just pretty. It has to work. I create simple, smooth and pleasant interfaces to use (even for aunt Josiane).',
    'services.uiux.feature1': 'User research',
    'services.uiux.feature2': 'Clean wireframes',
    'services.uiux.feature3': 'Pixel-perfect mockups',
    'services.uiux.feature4': 'Testing to see if everything holds',
    'services.webDev.title': 'Print Design',
    'services.webDev.desc': 'Stuff you can touch. Flyers, cards, posters — everything that\'s read with eyes and hands.',
    'services.webDev.feature1': 'Careful layout',
    'services.webDev.feature2': 'Good typography choice (not Comic Sans, don\'t worry)',
    'services.webDev.feature3': 'Perfect color harmonies',
    'services.webDev.feature4': 'Print-ready files',
    'services.mobile.title': 'Mobile Design',
    'services.mobile.desc': 'Your app deserves better than a default template. I make you a clear, intuitive, and pleasant interface to use on the metro.',
    'services.mobile.feature1': 'iOS & Android Design',
    'services.mobile.feature2': 'Well-thought user journey',
    'services.mobile.feature3': 'Smooth onboarding',
    'services.mobile.feature4': 'Icons, menus, and all the little details that make the difference',
    'services.creative.title': 'Creative Direction',
    'services.creative.desc': 'You have ideas, but you want everything to be aligned, clean and coherent? I take the wheel, you give me the direction.',
    'services.creative.feature1': 'Art direction',
    'services.creative.feature2': 'Campaign strategy',
    'services.creative.feature3': 'Content planning',
    'services.creative.feature4': 'Brand positioning',
    'services.motion.title': 'Motion Design & Video',
    'services.motion.desc': 'Content that moves well. I edit, animate, give rhythm to your visual communication.',
    'services.motion.feature1': 'Stylish logo animations',
    'services.motion.feature2': 'Dynamic video editing',
    'services.motion.feature3': 'Teasers, trailers, reels, stories...',
    'services.motion.feature4': 'Micro-animations and smooth effects',
    'services.startProject': 'Start a Project',

    // Testimonials Section
    'testimonials.subtitle': 'Client Reviews',
    'testimonials.title': 'What clients say',
    'testimonials.description': 'Feedback from clients who trusted me with their creative projects.',
    'testimonials.trustedBy': 'Trusted by',
    'testimonials.trustedByDesc': 'Companies and startups who chose my creative expertise',

    // Contact Section
    'contact.subtitle': 'Let\'s Discuss',
    'contact.title1': 'Let\'s',
    'contact.title2': 'discuss?',
    'contact.description': 'You have an idea? Need visual help? Or just want to know if it could work between us?',
    'contact.getInTouch': 'Get in Touch',
    'contact.getInTouchDesc': 'Write to me, I respond quickly (and always with pleasure).',
    'contact.email': 'Email',
    'contact.emailDesc': 'For all your creative projects',
    'contact.phone': 'Phone',
    'contact.phoneDesc': 'Available for urgent projects',
    'contact.location': 'Location',
    'contact.locationDesc': 'Based in the Lake Geneva region',
    'contact.followMe': 'Follow Me',
    'contact.sendMessage': 'Send a Message',
    'contact.name': 'Your Name',
    'contact.namePlaceholder': 'Enter your name',
    'contact.emailPlaceholder': 'Enter your email',
    'contact.subject': 'Subject',
    'contact.subjectPlaceholder': 'What\'s this about?',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Tell me about your project...',
    'contact.sendBtn': 'Send Message',

    // Footer
    'footer.description': 'Creative solutions specialist based in Switzerland. I transform your ideas into impactful visual experiences.',
    'footer.quickLinks': 'Quick Links',
    'footer.services': 'Services',
    'footer.brandIdentity': 'Brand Identity',
    'footer.uiuxDesign': 'UI/UX Design',
    'footer.webDevelopment': 'Web Development',
    'footer.motionGraphics': 'Motion Graphics',
    'footer.madeWith': 'Made with',
    'footer.inSwitzerland': 'in Switzerland',
    'footer.allRights': '© 2024 Theo Blondel. All rights reserved.'
  },
  fr: {
    // Navigation
    'nav.about': 'À propos',
    'nav.work': 'Projets',
    'nav.services': 'Services',
    'nav.contact': 'Contact',
    'nav.letsTalk': 'On en parle ?',

    // Hero Section
    'hero.subtitle': 'Médiamaticien',
    'hero.greeting': 'Yo, moi c\'est Theo Blondel.',
    'hero.title1': 'Solutions',
    'hero.title2': 'créatives polyvalentes',
    'hero.description': 'Je suis médiamaticien en Suisse, et je transforme tes idées en projets visuels propres, impactants, et vraiment stylés.',
    'hero.contactMe': 'On en parle ?',
    'hero.watchDemo': 'Voir la démo',
    'hero.yearsExperience': 'Années d\'expérience',
    'hero.projectsDelivered': 'Projets livrés',
    'hero.clientSatisfaction': 'Satisfaction client',
    'hero.clientsWorldwide': 'Clients dans le monde',
    'hero.service1.title': 'Identité de Marque',
    'hero.service1.desc': 'Logos pro et identité visuelle complète',
    'hero.service2.title': 'UI/UX Design',
    'hero.service2.desc': 'Interfaces intuitives et engageantes',
    'hero.service3.title': 'Motion Graphics',
    'hero.service3.desc': 'Animations dynamiques et vidéos',
    'hero.service4.title': 'Design Print',
    'hero.service4.desc': 'Supports print professionnels',

    // About Section
    'about.subtitle': 'Mon Parcours',
    'about.title1': 'Créatif dans le fond,',
    'about.title2': 'efficace dans la forme.',
    'about.description1': 'J\'ai commencé comme beaucoup : avec des montages YouTube à 15 ans, la tête dans les pixels et les effets sonores. Minecraft, Fortnite, Call of... J\'ai passé des heures à tester, à bidouiller, à chercher ce qui marche.',
    'about.description2': 'Puis le dessin est arrivé. Ensuite, la médiamatique. Et là, j\'ai pigé : je veux faire ça. Créer. Concevoir. Donner vie à des idées visuelles qui parlent aux gens.',
    'about.skill1.title': 'Adobe Creative Suite',
    'about.skill1.desc': 'Maîtrise professionnelle de la suite complète',
    'about.skill2.title': 'DaVinci Resolve',
    'about.skill2.desc': 'Montage vidéo avancé et étalonnage',
    'about.skill3.title': 'Autodesk Suite',
    'about.skill3.desc': 'Modélisation 3D et animation',
    'about.skill4.title': 'Figma (je sais)',
    'about.skill4.desc': 'Design UI/UX et prototypage',

    // Portfolio Section
    'portfolio.subtitle': 'Mes Projets',
    'portfolio.title1': 'Quelques trucs',
    'portfolio.title2': 'que j\'ai kiffé faire',
    'portfolio.description': 'Une sélection de projets qui montrent mon approche créative et mon expertise technique.',
    'portfolio.category.all': 'Tous',
    'portfolio.category.webApp': 'Web App',
    'portfolio.category.branding': 'Branding',
    'portfolio.category.mobile': 'Mobile',
    'portfolio.category.animation': 'Animation',
    'portfolio.category.audio': 'Audio',
    'portfolio.viewAllBehance': 'Voir tout sur Behance',

    // Services Section
    'services.subtitle': 'Ce que je peux faire',
    'services.title': 'Ce que je peux faire pour toi',
    'services.description': 'Des solutions créatives complètes adaptées à tes besoins et objectifs.',
    'services.brandIdentity.title': 'Identité de Marque',
    'services.brandIdentity.desc': 'Besoin d\'un logo qui claque et d\'une image qui raconte qui tu es ? Je t\'aide à construire une vraie identité — pas juste un logo vite fait.',
    'services.brandIdentity.feature1': 'Logo (pro, pas sur Canva)',
    'services.brandIdentity.feature2': 'Charte graphique claire',
    'services.brandIdentity.feature3': 'Identité visuelle cohérente',
    'services.brandIdentity.feature4': 'Positionnement de marque qui tient la route',
    'services.uiux.title': 'UI/UX Design',
    'services.uiux.desc': 'Un bon design, c\'est pas juste joli. Faut que ça fonctionne. Je crée des interfaces simples, fluides et agréables à utiliser (même pour tata Josiane).',
    'services.uiux.feature1': 'Recherche utilisateur',
    'services.uiux.feature2': 'Wireframes propres',
    'services.uiux.feature3': 'Maquettes pixel-perfect',
    'services.uiux.feature4': 'Tests pour voir si tout tient',
    'services.webDev.title': 'Design Print',
    'services.webDev.desc': 'Des trucs qu\'on peut toucher. Flyers, cartes, affiches — tout ce qui se lit avec les yeux et les mains.',
    'services.webDev.feature1': 'Mise en page soignée',
    'services.webDev.feature2': 'Bon choix de typo (pas Comic Sans, t\'inquiète)',
    'services.webDev.feature3': 'Harmonies de couleurs au petit oignon',
    'services.webDev.feature4': 'Fichiers prêts pour l\'imprimeur',
    'services.mobile.title': 'Design Mobile',
    'services.mobile.desc': 'Ton app mérite mieux qu\'un template par défaut. Je te fais une interface claire, intuitive, et agréable à utiliser dans le métro.',
    'services.mobile.feature1': 'Design iOS & Android',
    'services.mobile.feature2': 'Parcours utilisateur bien pensé',
    'services.mobile.feature3': 'Onboarding fluide',
    'services.mobile.feature4': 'Icônes, menus, et tous les petits détails qui font la diff',
    'services.creative.title': 'Direction Créative',
    'services.creative.desc': 'T\'as les idées, mais tu veux que tout soit aligné, clean et cohérent ? Je prends le volant, tu me donnes la direction.',
    'services.creative.feature1': 'Direction artistique',
    'services.creative.feature2': 'Stratégie de campagne',
    'services.creative.feature3': 'Conseils stylés mais utiles',
    'services.creative.feature4': 'Vision globale du projet',
    'services.motion.title': 'Motion Design & Vidéo',
    'services.motion.desc': 'Du contenu qui bouge bien. Je monte, j\'anime, je donne du rythme à ta com\' visuelle.',
    'services.motion.feature1': 'Animation de logos stylés',
    'services.motion.feature2': 'Montages vidéos dynamiques',
    'services.motion.feature3': 'Teasers, trailers, reels, stories…',
    'services.motion.feature4': 'Micro-animations et effets smooth',
    'services.startProject': 'Démarrer un projet',

    // Testimonials Section
    'testimonials.subtitle': 'Avis Clients',
    'testimonials.title': 'Ce qu\'en disent mes clients',
    'testimonials.description': 'Les retours de clients qui m\'ont fait confiance pour leurs projets créatifs.',
    'testimonials.trustedBy': 'Ils me font confiance',
    'testimonials.trustedByDesc': 'Entreprises et startups qui ont choisi mon expertise créative',

    // Contact Section
    'contact.subtitle': 'On discute ?',
    'contact.title1': 'On',
    'contact.title2': 'discute ?',
    'contact.description': 'T\'as une idée ? T\'as besoin d\'un coup de main visuel ? Ou juste envie de savoir si ça peut coller entre nous ?',
    'contact.getInTouch': 'Prendre Contact',
    'contact.getInTouchDesc': 'Écris-moi, je réponds vite (et toujours avec plaisir).',
    'contact.email': 'Email',
    'contact.emailDesc': 'Pour tous tes projets créatifs',
    'contact.phone': 'Téléphone',
    'contact.phoneDesc': 'Disponible pour les projets urgents',
    'contact.location': 'Localisation',
    'contact.locationDesc': 'Basé dans la région lémanique',
    'contact.followMe': 'Me suivre',
    'contact.sendMessage': 'Envoyer un message',
    'contact.name': 'Ton nom',
    'contact.namePlaceholder': 'Entre ton nom',
    'contact.emailPlaceholder': 'Entre ton email',
    'contact.subject': 'Sujet',
    'contact.subjectPlaceholder': 'C\'est à propos de quoi ?',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Parle-moi de ton projet...',
    'contact.sendBtn': 'Envoyer le message',

    // Footer
    'footer.description': 'Spécialiste en solutions créatives basé en Suisse. Je transforme tes idées en expériences visuelles impactantes.',
    'footer.quickLinks': 'Liens Rapides',
    'footer.services': 'Services',
    'footer.brandIdentity': 'Identité de Marque',
    'footer.uiuxDesign': 'UI/UX Design',
    'footer.webDevelopment': 'Développement Web',
    'footer.motionGraphics': 'Motion Graphics',
    'footer.madeWith': 'Fait avec',
    'footer.inSwitzerland': 'en Suisse',
    'footer.allRights': '© 2024 Theo Blondel. Tous droits réservés.'
  },
  es: {
    // Navigation
    'nav.about': 'Acerca de',
    'nav.work': 'Trabajo',
    'nav.services': 'Servicios',
    'nav.contact': 'Contacto',
    'nav.letsTalk': 'Hablemos',

    // Hero Section
    'hero.subtitle': 'Soluciones Creativas',
    'hero.greeting': 'Hola, soy Theo Blondel.',
    'hero.title1': 'Soluciones',
    'hero.title2': 'Creativas',
    'hero.description': 'Soy un mediamático en Suiza, y transformo tus ideas en proyectos visuales limpios, impactantes y realmente elegantes.',
    'hero.contactMe': '¿Hablamos?',
    'hero.watchDemo': 'Ver Demo',
    'hero.yearsExperience': 'Años de Experiencia',
    'hero.projectsDelivered': 'Proyectos Entregados',
    'hero.clientSatisfaction': 'Satisfacción del Cliente',
    'hero.clientsWorldwide': 'Clientes en el Mundo',
    'hero.service1.title': 'Identidad de Marca',
    'hero.service1.desc': 'Logos profesionales e identidad visual',
    'hero.service2.title': 'Diseño UI/UX',
    'hero.service2.desc': 'Interfaces intuitivas y atractivas',
    'hero.service3.title': 'Motion Graphics',
    'hero.service3.desc': 'Animaciones dinámicas y videos',
    'hero.service4.title': 'Diseño Impreso',
    'hero.service4.desc': 'Materiales impresos profesionales',

    // About Section
    'about.subtitle': 'Mi Trayectoria',
    'about.title1': 'Creativo en el fondo,',
    'about.title2': 'eficiente en la forma.',
    'about.description1': 'Empecé como muchos: con montajes de YouTube a los 15 años, la cabeza en píxeles y efectos de sonido. Minecraft, Fortnite, Call of... Pasé horas probando, experimentando, buscando lo que funciona.',
    'about.description2': 'Luego llegó el dibujo. Después, la mediamática. Y ahí lo entendí: quiero hacer esto. Crear. Diseñar. Dar vida a ideas visuales que hablen a la gente.',
    'about.skill1.title': 'Adobe Creative Suite',
    'about.skill1.desc': 'Dominio profesional de la suite completa',
    'about.skill2.title': 'DaVinci Resolve',
    'about.skill2.desc': 'Edición de video avanzada y corrección de color',
    'about.skill3.title': 'Suite Autodesk',
    'about.skill3.desc': 'Modelado 3D y animación',
    'about.skill4.title': 'Figma',
    'about.skill4.desc': 'Diseño UI/UX y prototipado',

    // Portfolio Section
    'portfolio.subtitle': 'Mis Proyectos',
    'portfolio.title1': 'Algunas cosas',
    'portfolio.title2': 'que me encantó hacer',
    'portfolio.description': 'Una selección de proyectos que muestran mi enfoque creativo y experiencia técnica.',
    'portfolio.category.all': 'Todos',
    'portfolio.category.webApp': 'App Web',
    'portfolio.category.branding': 'Branding',
    'portfolio.category.mobile': 'Móvil',
    'portfolio.category.animation': 'Animación',
    'portfolio.category.audio': 'Audio',
    'portfolio.viewAllBehance': 'Ver todo en Behance',

    // Services Section
    'services.subtitle': 'Lo que puedo hacer',
    'services.title': 'Lo que puedo hacer por ti',
    'services.description': 'Soluciones creativas completas adaptadas a tus necesidades y objetivos.',
    'services.brandIdentity.title': 'Identidad de Marca',
    'services.brandIdentity.desc': '¿Necesitas un logo que impacte y una imagen que cuente quién eres? Te ayudo a construir una identidad real, no solo un logo rápido.',
    'services.brandIdentity.feature1': 'Logo profesional (no en Canva)',
    'services.brandIdentity.feature2': 'Manual de marca claro',
    'services.brandIdentity.feature3': 'Identidad visual coherente',
    'services.brandIdentity.feature4': 'Posicionamiento de marca sólido',
    'services.uiux.title': 'Diseño UI/UX',
    'services.uiux.desc': 'Un buen diseño no es solo bonito. Tiene que funcionar. Creo interfaces simples, fluidas y agradables de usar.',
    'services.uiux.feature1': 'Investigación de usuarios',
    'services.uiux.feature2': 'Wireframes limpios',
    'services.uiux.feature3': 'Mockups pixel-perfect',
    'services.uiux.feature4': 'Pruebas para ver si todo funciona',
    'services.webDev.title': 'Diseño Impreso',
    'services.webDev.desc': 'Cosas que puedes tocar. Flyers, tarjetas, carteles: todo lo que se lee con los ojos y las manos.',
    'services.webDev.feature1': 'Maquetación cuidadosa',
    'services.webDev.feature2': 'Buena elección tipográfica',
    'services.webDev.feature3': 'Armonías de color perfectas',
    'services.webDev.feature4': 'Archivos listos para imprenta',
    'services.mobile.title': 'Diseño Móvil',
    'services.mobile.desc': 'Tu app merece algo mejor que una plantilla por defecto. Te hago una interfaz clara, intuitiva y agradable de usar en el metro.',
    'services.mobile.feature1': 'Diseño iOS y Android',
    'services.mobile.feature2': 'Recorrido de usuario bien pensado',
    'services.mobile.feature3': 'Onboarding fluido',
    'services.mobile.feature4': 'Iconos, menús y todos los detalles que marcan la diferencia',
    'services.creative.title': 'Dirección Creativa',
    'services.creative.desc': 'Tienes las ideas, pero quieres que todo esté alineado, limpio y coherente? Tomo el volante, tú me das la dirección.',
    'services.creative.feature1': 'Dirección artística',
    'services.creative.feature2': 'Estrategia de campaña',
    'services.creative.feature3': 'Consejos útiles y con estilo',
    'services.creative.feature4': 'Visión global del proyecto',
    'services.motion.title': 'Motion Design y Video',
    'services.motion.desc': 'Contenido que se mueve bien. Edito, animo, doy ritmo a tu comunicación visual.',
    'services.motion.feature1': 'Animaciones de logos elegantes',
    'services.motion.feature2': 'Edición de video dinámica',
    'services.motion.feature3': 'Teasers, trailers, reels, stories...',
    'services.motion.feature4': 'Micro-animaciones y efectos suaves',
    'services.startProject': 'Iniciar un Proyecto',

    // Testimonials Section
    'testimonials.subtitle': 'Reseñas de Clientes',
    'testimonials.title': 'Lo que dicen los clientes',
    'testimonials.description': 'Comentarios de clientes que confiaron en mí para sus proyectos creativos.',
    'testimonials.trustedBy': 'Confían en mí',
    'testimonials.trustedByDesc': 'Empresas y startups que eligieron mi experiencia creativa',

    // Contact Section
    'contact.subtitle': '¿Hablamos?',
    'contact.title1': '¿Hablamos?',
    'contact.title2': '',
    'contact.description': '¿Tienes una idea? ¿Necesitas ayuda visual? ¿O solo quieres saber si podríamos trabajar juntos?',
    'contact.getInTouch': 'Ponte en Contacto',
    'contact.getInTouchDesc': 'Escríbeme, respondo rápido (y siempre con gusto).',
    'contact.email': 'Email',
    'contact.emailDesc': 'Para todos tus proyectos creativos',
    'contact.phone': 'Teléfono',
    'contact.phoneDesc': 'Disponible para proyectos urgentes',
    'contact.location': 'Ubicación',
    'contact.locationDesc': 'Basado en la región del Lago Lemán',
    'contact.followMe': 'Sígueme',
    'contact.sendMessage': 'Enviar un Mensaje',
    'contact.name': 'Tu Nombre',
    'contact.namePlaceholder': 'Ingresa tu nombre',
    'contact.emailPlaceholder': 'Ingresa tu email',
    'contact.subject': 'Asunto',
    'contact.subjectPlaceholder': '¿De qué se trata?',
    'contact.message': 'Mensaje',
    'contact.messagePlaceholder': 'Cuéntame sobre tu proyecto...',
    'contact.sendBtn': 'Enviar Mensaje',

    // Footer
    'footer.description': 'Especialista en soluciones creativas basado en Suiza. Transformo tus ideas en experiencias visuales impactantes.',
    'footer.quickLinks': 'Enlaces Rápidos',
    'footer.services': 'Servicios',
    'footer.brandIdentity': 'Identidad de Marca',
    'footer.uiuxDesign': 'Diseño UI/UX',
    'footer.webDevelopment': 'Desarrollo Web',
    'footer.motionGraphics': 'Motion Graphics',
    'footer.madeWith': 'Hecho con',
    'footer.inSwitzerland': 'en Suiza',
    'footer.allRights': '© 2024 Theo Blondel. Todos los derechos reservados.'
  },
  ru: {
    // Navigation
    'nav.about': 'О себе',
    'nav.work': 'Работы',
    'nav.services': 'Услуги',
    'nav.contact': 'Контакты',
    'nav.letsTalk': 'Поговорим',

    // Hero Section
    'hero.subtitle': 'Креативные Решения',
    'hero.greeting': 'Привет, я Тео Блондель.',
    'hero.title1': 'Креативные',
    'hero.title2': 'Решения',
    'hero.description': 'Я медиаматик из Швейцарии, и я превращаю ваши идеи в чистые, впечатляющие и действительно стильные визуальные проекты.',
    'hero.contactMe': 'Поговорим?',
    'hero.watchDemo': 'Смотреть Демо',
    'hero.yearsExperience': 'Лет Опыта',
    'hero.projectsDelivered': 'Проектов Выполнено',
    'hero.clientSatisfaction': 'Удовлетворенность Клиентов',
    'hero.clientsWorldwide': 'Клиентов по Всему Миру',
    'hero.service1.title': 'Фирменный Стиль',
    'hero.service1.desc': 'Профессиональные логотипы и визуальная идентичность',
    'hero.service2.title': 'UI/UX Дизайн',
    'hero.service2.desc': 'Интуитивные и привлекательные интерфейсы',
    'hero.service3.title': 'Моушн Графика',
    'hero.service3.desc': 'Динамичные анимации и видео',
    'hero.service4.title': 'Печатный Дизайн',
    'hero.service4.desc': 'Профессиональные печатные материалы',

    // About Section
    'about.subtitle': 'Мой Путь',
    'about.title1': 'Креативный по сути,',
    'about.title2': 'эффективный по форме.',
    'about.description1': 'Я начинал как многие: с монтажа YouTube в 15 лет, с головой в пикселях и звуковых эффектах. Minecraft, Fortnite, Call of... Я проводил часы, тестируя, экспериментируя, ища то, что работает.',
    'about.description2': 'Потом пришло рисование. Затем медиаматика. И тут я понял: я хочу заниматься этим. Создавать. Проектировать. Воплощать визуальные идеи, которые говорят с людьми.',
    'about.skill1.title': 'Adobe Creative Suite',
    'about.skill1.desc': 'Профессиональное владение полным пакетом',
    'about.skill2.title': 'DaVinci Resolve',
    'about.skill2.desc': 'Продвинутый видеомонтаж и цветокоррекция',
    'about.skill3.title': 'Autodesk Suite',
    'about.skill3.desc': '3D моделирование и анимация',
    'about.skill4.title': 'Figma',
    'about.skill4.desc': 'UI/UX дизайн и прототипирование',

    // Portfolio Section
    'portfolio.subtitle': 'Мои Проекты',
    'portfolio.title1': 'Некоторые вещи,',
    'portfolio.title2': 'которые мне понравилось делать',
    'portfolio.description': 'Подборка проектов, демонстрирующих мой креативный подход и техническую экспертизу.',
    'portfolio.category.all': 'Все',
    'portfolio.category.webApp': 'Веб-приложения',
    'portfolio.category.branding': 'Брендинг',
    'portfolio.category.mobile': 'Мобильные',
    'portfolio.category.animation': 'Анимация',
    'portfolio.category.audio': 'Аудио',
    'portfolio.viewAllBehance': 'Смотреть все на Behance',

    // Services Section
    'services.subtitle': 'Что я могу делать',
    'services.title': 'Что я могу сделать для вас',
    'services.description': 'Комплексные креативные решения, адаптированные под ваши потребности и цели.',
    'services.brandIdentity.title': 'Фирменный Стиль',
    'services.brandIdentity.desc': 'Нужен логотип, который впечатляет, и образ, который рассказывает, кто вы? Я помогу построить настоящую идентичность — не просто быстрый логотип.',
    'services.brandIdentity.feature1': 'Профессиональный логотип (не в Canva)',
    'services.brandIdentity.feature2': 'Четкий брендбук',
    'services.brandIdentity.feature3': 'Последовательная визуальная идентичность',
    'services.brandIdentity.feature4': 'Надежное позиционирование бренда',
    'services.uiux.title': 'UI/UX Дизайн',
    'services.uiux.desc': 'Хороший дизайн — это не просто красиво. Он должен работать. Я создаю простые, плавные и приятные в использовании интерфейсы.',
    'services.uiux.feature1': 'Исследование пользователей',
    'services.uiux.feature2': 'Чистые вайрфреймы',
    'services.uiux.feature3': 'Пиксель-перфект макеты',
    'services.uiux.feature4': 'Тестирование, чтобы убедиться, что все работает',
    'services.webDev.title': 'Печатный Дизайн',
    'services.webDev.desc': 'Вещи, которые можно потрогать. Флаеры, карточки, постеры — все, что читается глазами и руками.',
    'services.webDev.feature1': 'Тщательная верстка',
    'services.webDev.feature2': 'Хороший выбор типографики',
    'services.webDev.feature3': 'Идеальные цветовые гармонии',
    'services.webDev.feature4': 'Файлы, готовые для печати',
    'services.mobile.title': 'Мобильный Дизайн',
    'services.mobile.desc': 'Ваше приложение заслуживает большего, чем стандартный шаблон. Я создам четкий, интуитивный и приятный в использовании интерфейс.',
    'services.mobile.feature1': 'Дизайн для iOS и Android',
    'services.mobile.feature2': 'Продуманный пользовательский путь',
    'services.mobile.feature3': 'Плавный онбординг',
    'services.mobile.feature4': 'Иконки, меню и все мелкие детали, которые имеют значение',
    'services.creative.title': 'Креативное Руководство',
    'services.creative.desc': 'У вас есть идеи, но вы хотите, чтобы все было выровнено, чисто и последовательно? Я беру руль, вы даете направление.',
    'services.creative.feature1': 'Арт-директорство',
    'services.creative.feature2': 'Стратегия кампании',
    'services.creative.feature3': 'Стильные, но полезные советы',
    'services.creative.feature4': 'Глобальное видение проекта',
    'services.motion.title': 'Моушн Дизайн и Видео',
    'services.motion.desc': 'Контент, который хорошо движется. Я монтирую, анимирую, задаю ритм вашей визуальной коммуникации.',
    'services.motion.feature1': 'Стильные анимации логотипов',
    'services.motion.feature2': 'Динамичный видеомонтаж',
    'services.motion.feature3': 'Тизеры, трейлеры, рилс, сторис...',
    'services.motion.feature4': 'Микро-анимации и плавные эффекты',
    'services.startProject': 'Начать Проект',

    // Testimonials Section
    'testimonials.subtitle': 'Отзывы Клиентов',
    'testimonials.title': 'Что говорят клиенты',
    'testimonials.description': 'Отзывы клиентов, которые доверили мне свои креативные проекты.',
    'testimonials.trustedBy': 'Мне доверяют',
    'testimonials.trustedByDesc': 'Компании и стартапы, которые выбрали мою креативную экспертизу',

    // Contact Section
    'contact.subtitle': 'Поговорим?',
    'contact.title1': 'Поговорим?',
    'contact.title2': '',
    'contact.description': 'У вас есть идея? Нужна визуальная помощь? Или просто хотите узнать, сможем ли мы работать вместе?',
    'contact.getInTouch': 'Связаться',
    'contact.getInTouchDesc': 'Напишите мне, я отвечаю быстро (и всегда с удовольствием).',
    'contact.email': 'Email',
    'contact.emailDesc': 'Для всех ваших креативных проектов',
    'contact.phone': 'Телефон',
    'contact.phoneDesc': 'Доступен для срочных проектов',
    'contact.location': 'Местоположение',
    'contact.locationDesc': 'Базируюсь в регионе Женевского озера',
    'contact.followMe': 'Подписаться',
    'contact.sendMessage': 'Отправить Сообщение',
    'contact.name': 'Ваше Имя',
    'contact.namePlaceholder': 'Введите ваше имя',
    'contact.emailPlaceholder': 'Введите ваш email',
    'contact.subject': 'Тема',
    'contact.subjectPlaceholder': 'О чем речь?',
    'contact.message': 'Сообщение',
    'contact.messagePlaceholder': 'Расскажите о вашем проекте...',
    'contact.sendBtn': 'Отправить Сообщение',

    // Footer
    'footer.description': 'Специалист по креативным решениям из Швейцарии. Превращаю ваши идеи в впечатляющие визуальные впечатления.',
    'footer.quickLinks': 'Быстрые Ссылки',
    'footer.services': 'Услуги',
    'footer.brandIdentity': 'Фирменный Стиль',
    'footer.uiuxDesign': 'UI/UX Дизайн',
    'footer.webDevelopment': 'Веб-разработка',
    'footer.motionGraphics': 'Моушн Графика',
    'footer.madeWith': 'Сделано с',
    'footer.inSwitzerland': 'в Швейцарии',
    'footer.allRights': '© 2024 Тео Блондель. Все права защищены.'
  },
  zh: {
    // Navigation
    'nav.about': '关于',
    'nav.work': '作品',
    'nav.services': '服务',
    'nav.contact': '联系',
    'nav.letsTalk': '聊聊吧',

    // Hero Section
    'hero.subtitle': '创意解决方案',
    'hero.greeting': '嗨，我是Theo Blondel。',
    'hero.title1': '创意',
    'hero.title2': '解决方案',
    'hero.description': '我是瑞士的媒体技术专家，将您的想法转化为干净、有影响力且真正时尚的视觉项目。',
    'hero.contactMe': '聊聊吧？',
    'hero.watchDemo': '观看演示',
    'hero.yearsExperience': '年经验',
    'hero.projectsDelivered': '项目交付',
    'hero.clientSatisfaction': '客户满意度',
    'hero.clientsWorldwide': '全球客户',
    'hero.service1.title': '品牌标识',
    'hero.service1.desc': '专业标志和视觉识别',
    'hero.service2.title': 'UI/UX设计',
    'hero.service2.desc': '直观且引人入胜的界面',
    'hero.service3.title': '动态图形',
    'hero.service3.desc': '动态动画和视频',
    'hero.service4.title': '印刷设计',
    'hero.service4.desc': '专业印刷材料',

    // About Section
    'about.subtitle': '我的历程',
    'about.title1': '内心创意，',
    'about.title2': '形式高效。',
    'about.description1': '我像许多人一样开始：15岁时制作YouTube剪辑，沉浸在像素和音效中。Minecraft、Fortnite、Call of...我花了几个小时测试、摸索、寻找有效的方法。',
    'about.description2': '然后绘画来了。接着是媒体技术。在那里，我明白了：我想做这个。创造。设计。让视觉想法活起来，与人们对话。',
    'about.skill1.title': 'Adobe Creative Suite',
    'about.skill1.desc': '完整套件的专业掌握',
    'about.skill2.title': 'DaVinci Resolve',
    'about.skill2.desc': '高级视频编辑和调色',
    'about.skill3.title': 'Autodesk套件',
    'about.skill3.desc': '3D建模和动画',
    'about.skill4.title': 'Figma',
    'about.skill4.desc': 'UI/UX设计和原型制作',

    // Portfolio Section
    'portfolio.subtitle': '我的项目',
    'portfolio.title1': '一些我',
    'portfolio.title2': '喜欢做的东西',
    'portfolio.description': '展示我的创意方法和技术专长的项目精选。',
    'portfolio.category.all': '全部',
    'portfolio.category.webApp': '网页应用',
    'portfolio.category.branding': '品牌',
    'portfolio.category.mobile': '移动端',
    'portfolio.category.animation': '动画',
    'portfolio.category.audio': '音频',
    'portfolio.viewAllBehance': '在Behance查看全部',

    // Services Section
    'services.subtitle': '我能做什么',
    'services.title': '我能为您做什么',
    'services.description': '根据您的需求和目标量身定制的完整创意解决方案。',
    'services.brandIdentity.title': '品牌标识',
    'services.brandIdentity.desc': '需要一个令人印象深刻的标志和讲述您身份的形象？我帮助您建立真正的身份——不只是一个快速标志。',
    'services.brandIdentity.feature1': '专业标志（不在Canva上）',
    'services.brandIdentity.feature2': '清晰的品牌指南',
    'services.brandIdentity.feature3': '一致的视觉识别',
    'services.brandIdentity.feature4': '可靠的品牌定位',
    'services.uiux.title': 'UI/UX设计',
    'services.uiux.desc': '好的设计不只是漂亮。它必须有效。我创建简单、流畅且使用愉快的界面。',
    'services.uiux.feature1': '用户研究',
    'services.uiux.feature2': '清晰的线框图',
    'services.uiux.feature3': '像素完美的模型',
    'services.uiux.feature4': '测试以确保一切正常',
    'services.webDev.title': '印刷设计',
    'services.webDev.desc': '可以触摸的东西。传单、卡片、海报——所有用眼睛和手阅读的东西。',
    'services.webDev.feature1': '精心布局',
    'services.webDev.feature2': '良好的字体选择',
    'services.webDev.feature3': '完美的色彩和谐',
    'services.webDev.feature4': '印刷就绪文件',
    'services.mobile.title': '移动设计',
    'services.mobile.desc': '您的应用值得比默认模板更好的东西。我为您制作清晰、直观且在地铁上使用愉快的界面。',
    'services.mobile.feature1': 'iOS和Android设计',
    'services.mobile.feature2': '深思熟虑的用户旅程',
    'services.mobile.feature3': '流畅的入门',
    'services.mobile.feature4': '图标、菜单和所有产生差异的小细节',
    'services.creative.title': '创意指导',
    'services.creative.desc': '您有想法，但希望一切都对齐、干净且一致？我掌舵，您给我方向。',
    'services.creative.feature1': '艺术指导',
    'services.creative.feature2': '活动策略',
    'services.creative.feature3': '时尚但有用的建议',
    'services.creative.feature4': '项目的全球视野',
    'services.motion.title': '动态设计和视频',
    'services.motion.desc': '移动良好的内容。我编辑、动画，为您的视觉传播赋予节奏。',
    'services.motion.feature1': '时尚的标志动画',
    'services.motion.feature2': '动态视频编辑',
    'services.motion.feature3': '预告片、拖车、卷轴、故事...',
    'services.motion.feature4': '微动画和流畅效果',
    'services.startProject': '开始项目',

    // Testimonials Section
    'testimonials.subtitle': '客户评价',
    'testimonials.title': '客户怎么说',
    'testimonials.description': '信任我处理他们创意项目的客户反馈。',
    'testimonials.trustedBy': '信任我的',
    'testimonials.trustedByDesc': '选择我的创意专长的公司和初创企业',

    // Contact Section
    'contact.subtitle': '聊聊吧？',
    'contact.title1': '聊聊吧？',
    'contact.title2': '',
    'contact.description': '您有想法吗？需要视觉帮助？还是只想知道我们是否能合作？',
    'contact.getInTouch': '联系',
    'contact.getInTouchDesc': '给我写信，我回复很快（总是很高兴）。',
    'contact.email': '邮箱',
    'contact.emailDesc': '为您的所有创意项目',
    'contact.phone': '电话',
    'contact.phoneDesc': '可用于紧急项目',
    'contact.location': '位置',
    'contact.locationDesc': '位于日内瓦湖地区',
    'contact.followMe': '关注我',
    'contact.sendMessage': '发送消息',
    'contact.name': '您的姓名',
    'contact.namePlaceholder': '输入您的姓名',
    'contact.emailPlaceholder': '输入您的邮箱',
    'contact.subject': '主题',
    'contact.subjectPlaceholder': '这是关于什么的？',
    'contact.message': '消息',
    'contact.messagePlaceholder': '告诉我您的项目...',
    'contact.sendBtn': '发送消息',

    // Footer
    'footer.description': '瑞士创意解决方案专家。我将您的想法转化为有影响力的视觉体验。',
    'footer.quickLinks': '快速链接',
    'footer.services': '服务',
    'footer.brandIdentity': '品牌标识',
    'footer.uiuxDesign': 'UI/UX设计',
    'footer.webDevelopment': '网页开发',
    'footer.motionGraphics': '动态图形',
    'footer.madeWith': '制作于',
    'footer.inSwitzerland': '瑞士',
    'footer.allRights': '© 2024 Theo Blondel. 保留所有权利。'
  },
  ja: {
    // Navigation
    'nav.about': 'について',
    'nav.work': '作品',
    'nav.services': 'サービス',
    'nav.contact': 'お問い合わせ',
    'nav.letsTalk': 'お話しましょう',

    // Hero Section
    'hero.subtitle': 'クリエイティブソリューション',
    'hero.greeting': 'こんにちは、Theo Blondelです。',
    'hero.title1': 'クリエイティブ',
    'hero.title2': 'ソリューション',
    'hero.description': '私はスイスのメディアマティシャンで、あなたのアイデアをクリーンで印象的で本当にスタイリッシュなビジュアルプロジェクトに変換します。',
    'hero.contactMe': 'お話しましょうか？',
    'hero.watchDemo': 'デモを見る',
    'hero.yearsExperience': '年の経験',
    'hero.projectsDelivered': 'プロジェクト納品',
    'hero.clientSatisfaction': 'クライアント満足度',
    'hero.clientsWorldwide': '世界中のクライアント',
    'hero.service1.title': 'ブランドアイデンティティ',
    'hero.service1.desc': 'プロフェッショナルなロゴとビジュアルアイデンティティ',
    'hero.service2.title': 'UI/UXデザイン',
    'hero.service2.desc': '直感的で魅力的なインターフェース',
    'hero.service3.title': 'モーショングラフィックス',
    'hero.service3.desc': 'ダイナミックなアニメーションとビデオ',
    'hero.service4.title': 'プリントデザイン',
    'hero.service4.desc': 'プロフェッショナルな印刷物',

    // About Section
    'about.subtitle': '私の歩み',
    'about.title1': '心はクリエイティブ、',
    'about.title2': '形は効率的。',
    'about.description1': '私は多くの人と同じように始めました：15歳でYouTubeの編集、ピクセルと音響効果に夢中でした。Minecraft、Fortnite、Call of...何が機能するかを探して、何時間もテストし、いじくり回していました。',
    'about.description2': 'そして絵画が来ました。次にメディアマティック。そこで私は理解しました：これをやりたい。創造する。設計する。人々に語りかけるビジュアルアイデアに命を吹き込む。',
    'about.skill1.title': 'Adobe Creative Suite',
    'about.skill1.desc': '完全スイートのプロフェッショナルマスタリー',
    'about.skill2.title': 'DaVinci Resolve',
    'about.skill2.desc': '高度なビデオ編集とカラーグレーディング',
    'about.skill3.title': 'Autodesk Suite',
    'about.skill3.desc': '3Dモデリングとアニメーション',
    'about.skill4.title': 'Figma',
    'about.skill4.desc': 'UI/UXデザインとプロトタイピング',

    // Portfolio Section
    'portfolio.subtitle': '私のプロジェクト',
    'portfolio.title1': 'いくつかの',
    'portfolio.title2': '好きでやったもの',
    'portfolio.description': '私のクリエイティブアプローチと技術的専門知識を示すプロジェクトの選択。',
    'portfolio.category.all': 'すべて',
    'portfolio.category.webApp': 'ウェブアプリ',
    'portfolio.category.branding': 'ブランディング',
    'portfolio.category.mobile': 'モバイル',
    'portfolio.category.animation': 'アニメーション',
    'portfolio.category.audio': 'オーディオ',
    'portfolio.viewAllBehance': 'Behanceですべて見る',

    // Services Section
    'services.subtitle': '私ができること',
    'services.title': 'あなたのためにできること',
    'services.description': 'あなたのニーズと目標に合わせた完全なクリエイティブソリューション。',
    'services.brandIdentity.title': 'ブランドアイデンティティ',
    'services.brandIdentity.desc': 'インパクトのあるロゴとあなたが誰であるかを語るイメージが必要ですか？本当のアイデンティティを構築するお手伝いをします—ただの急ごしらえのロゴではありません。',
    'services.brandIdentity.feature1': 'プロフェッショナルロゴ（Canvaではない）',
    'services.brandIdentity.feature2': '明確なブランドガイドライン',
    'services.brandIdentity.feature3': '一貫したビジュアルアイデンティティ',
    'services.brandIdentity.feature4': '信頼できるブランドポジショニング',
    'services.uiux.title': 'UI/UXデザイン',
    'services.uiux.desc': '良いデザインは美しいだけではありません。機能しなければなりません。シンプルで滑らかで使いやすいインターフェースを作成します。',
    'services.uiux.feature1': 'ユーザーリサーチ',
    'services.uiux.feature2': 'クリーンなワイヤーフレーム',
    'services.uiux.feature3': 'ピクセルパーフェクトなモックアップ',
    'services.uiux.feature4': 'すべてが機能するかテスト',
    'services.webDev.title': 'プリントデザイン',
    'services.webDev.desc': '触れることができるもの。フライヤー、カード、ポスター—目と手で読むすべてのもの。',
    'services.webDev.feature1': '丁寧なレイアウト',
    'services.webDev.feature2': '良いタイポグラフィの選択',
    'services.webDev.feature3': '完璧な色の調和',
    'services.webDev.feature4': '印刷準備完了ファイル',
    'services.mobile.title': 'モバイルデザイン',
    'services.mobile.desc': 'あなたのアプリはデフォルトテンプレートよりも良いものに値します。地下鉄で使うのに明確で直感的で快適なインターフェースを作ります。',
    'services.mobile.feature1': 'iOSとAndroidデザイン',
    'services.mobile.feature2': 'よく考えられたユーザージャーニー',
    'services.mobile.feature3': 'スムーズなオンボーディング',
    'services.mobile.feature4': 'アイコン、メニュー、そして違いを生む小さな詳細すべて',
    'services.creative.title': 'クリエイティブディレクション',
    'services.creative.desc': 'アイデアはあるが、すべてが整列し、クリーンで一貫していることを望みますか？私がハンドルを握り、あなたが方向を教えてください。',
    'services.creative.feature1': 'アートディレクション',
    'services.creative.feature2': 'キャンペーン戦略',
    'services.creative.feature3': 'スタイリッシュだが有用なアドバイス',
    'services.creative.feature4': 'プロジェクトのグローバルビジョン',
    'services.motion.title': 'モーションデザインとビデオ',
    'services.motion.desc': 'よく動くコンテンツ。編集し、アニメートし、あなたのビジュアルコミュニケーションにリズムを与えます。',
    'services.motion.feature1': 'スタイリッシュなロゴアニメーション',
    'services.motion.feature2': 'ダイナミックなビデオ編集',
    'services.motion.feature3': 'ティーザー、トレーラー、リール、ストーリー...',
    'services.motion.feature4': 'マイクロアニメーションとスムーズエフェクト',
    'services.startProject': 'プロジェクトを開始',

    // Testimonials Section
    'testimonials.subtitle': 'クライアントレビュー',
    'testimonials.title': 'クライアントの声',
    'testimonials.description': 'クリエイティブプロジェクトを私に託してくれたクライアントからのフィードバック。',
    'testimonials.trustedBy': '信頼されています',
    'testimonials.trustedByDesc': '私のクリエイティブ専門知識を選んだ企業とスタートアップ',

    // Contact Section
    'contact.subtitle': 'お話しましょうか？',
    'contact.title1': 'お話し',
    'contact.title2': 'しましょうか？',
    'contact.description': 'アイデアはありますか？ビジュアルヘルプが必要ですか？それとも私たちが協力できるかどうか知りたいだけですか？',
    'contact.getInTouch': '連絡を取る',
    'contact.getInTouchDesc': '私に書いてください、すぐに返信します（いつも喜んで）。',
    'contact.email': 'メール',
    'contact.emailDesc': 'すべてのクリエイティブプロジェクトのために',
    'contact.phone': '電話',
    'contact.phoneDesc': '緊急プロジェクトに対応可能',
    'contact.location': '場所',
    'contact.locationDesc': 'レマン湖地域を拠点',
    'contact.followMe': 'フォローする',
    'contact.sendMessage': 'メッセージを送る',
    'contact.name': 'お名前',
    'contact.namePlaceholder': 'お名前を入力',
    'contact.emailPlaceholder': 'メールアドレスを入力',
    'contact.subject': '件名',
    'contact.subjectPlaceholder': '何についてですか？',
    'contact.message': 'メッセージ',
    'contact.messagePlaceholder': 'プロジェクトについて教えてください...',
    'contact.sendBtn': 'メッセージを送信',

    // Footer
    'footer.description': 'スイスを拠点とするクリエイティブソリューション専門家。あなたのアイデアをインパクトのあるビジュアル体験に変換します。',
    'footer.quickLinks': 'クイックリンク',
    'footer.services': 'サービス',
    'footer.brandIdentity': 'ブランドアイデンティティ',
    'footer.uiuxDesign': 'UI/UXデザイン',
    'footer.webDevelopment': 'ウェブ開発',
    'footer.motionGraphics': 'モーショングラフィックス',
    'footer.madeWith': '作られました',
    'footer.inSwitzerland': 'スイスで',
    'footer.allRights': '© 2024 Theo Blondel. すべての権利予約。'
  },
  de: {
    // Navigation
    'nav.about': 'Über mich',
    'nav.work': 'Arbeiten',
    'nav.services': 'Dienstleistungen',
    'nav.contact': 'Kontakt',
    'nav.letsTalk': 'Lass uns reden',

    // Hero Section
    'hero.subtitle': 'Kreative Lösungen',
    'hero.greeting': 'Hey, ich bin Theo Blondel.',
    'hero.title1': 'Kreative',
    'hero.title2': 'Lösungen',
    'hero.description': 'Ich bin Mediamatiker in der Schweiz und verwandle deine Ideen in saubere, wirkungsvolle und wirklich stylische visuelle Projekte.',
    'hero.contactMe': 'Lass uns reden?',
    'hero.watchDemo': 'Demo ansehen',
    'hero.yearsExperience': 'Jahre Erfahrung',
    'hero.projectsDelivered': 'Projekte geliefert',
    'hero.clientSatisfaction': 'Kundenzufriedenheit',
    'hero.clientsWorldwide': 'Kunden weltweit',
    'hero.service1.title': 'Markenidentität',
    'hero.service1.desc': 'Professionelle Logos und visuelle Identität',
    'hero.service2.title': 'UI/UX Design',
    'hero.service2.desc': 'Intuitive und ansprechende Benutzeroberflächen',
    'hero.service3.title': 'Motion Graphics',
    'hero.service3.desc': 'Dynamische Animationen und Videos',
    'hero.service4.title': 'Print Design',
    'hero.service4.desc': 'Professionelle Druckmaterialien',

    // About Section
    'about.subtitle': 'Mein Weg',
    'about.title1': 'Kreativ im Kern,',
    'about.title2': 'effizient in der Form.',
    'about.description1': 'Ich habe wie viele angefangen: mit YouTube-Montagen mit 15, den Kopf voller Pixel und Soundeffekte. Minecraft, Fortnite, Call of... Ich verbrachte Stunden damit zu testen, zu basteln, herauszufinden was funktioniert.',
    'about.description2': 'Dann kam das Zeichnen. Danach die Mediamatik. Und da hab ich\'s kapiert: Das will ich machen. Erschaffen. Gestalten. Visuelle Ideen zum Leben erwecken, die zu den Menschen sprechen.',
    'about.skill1.title': 'Adobe Creative Suite',
    'about.skill1.desc': 'Professionelle Beherrschung der kompletten Suite',
    'about.skill2.title': 'DaVinci Resolve',
    'about.skill2.desc': 'Fortgeschrittene Videobearbeitung und Farbkorrektur',
    'about.skill3.title': 'Autodesk Suite',
    'about.skill3.desc': '3D-Modellierung und Animation',
    'about.skill4.title': 'Figma',
    'about.skill4.desc': 'UI/UX Design und Prototyping',

    // Portfolio Section
    'portfolio.subtitle': 'Meine Projekte',
    'portfolio.title1': 'Einige Sachen,',
    'portfolio.title2': 'die ich gerne gemacht habe',
    'portfolio.description': 'Eine Auswahl von Projekten, die meinen kreativen Ansatz und meine technische Expertise zeigen.',
    'portfolio.category.all': 'Alle',
    'portfolio.category.webApp': 'Web App',
    'portfolio.category.branding': 'Branding',
    'portfolio.category.mobile': 'Mobile',
    'portfolio.category.animation': 'Animation',
    'portfolio.category.audio': 'Audio',
    'portfolio.viewAllBehance': 'Alle auf Behance ansehen',

    // Services Section
    'services.subtitle': 'Was ich kann',
    'services.title': 'Was ich für dich tun kann',
    'services.description': 'Komplette kreative Lösungen, angepasst an deine Bedürfnisse und Ziele.',
    'services.brandIdentity.title': 'Markenidentität',
    'services.brandIdentity.desc': 'Brauchst du ein Logo, das rockt und ein Image, das erzählt wer du bist? Ich helfe dir eine echte Identität aufzubauen — nicht nur ein schnelles Logo.',
    'services.brandIdentity.feature1': 'Professionelles Logo (nicht auf Canva)',
    'services.brandIdentity.feature2': 'Klare Markenrichtlinien',
    'services.brandIdentity.feature3': 'Kohärente visuelle Identität',
    'services.brandIdentity.feature4': 'Solide Markenpositionierung',
    'services.uiux.title': 'UI/UX Design',
    'services.uiux.desc': 'Gutes Design ist nicht nur hübsch. Es muss funktionieren. Ich erstelle einfache, flüssige und angenehm zu nutzende Interfaces.',
    'services.uiux.feature1': 'Benutzerforschung',
    'services.uiux.feature2': 'Saubere Wireframes',
    'services.uiux.feature3': 'Pixel-perfekte Mockups',
    'services.uiux.feature4': 'Tests um zu sehen ob alles hält',
    'services.webDev.title': 'Print Design',
    'services.webDev.desc': 'Sachen die man anfassen kann. Flyer, Karten, Plakate — alles was man mit Augen und Händen liest.',
    'services.webDev.feature1': 'Sorgfältiges Layout',
    'services.webDev.feature2': 'Gute Typografie-Wahl',
    'services.webDev.feature3': 'Perfekte Farbharmonien',
    'services.webDev.feature4': 'Druckfertige Dateien',
    'services.mobile.title': 'Mobile Design',
    'services.mobile.desc': 'Deine App verdient besser als ein Standard-Template. Ich mache dir ein klares, intuitives und angenehm zu nutzendes Interface.',
    'services.mobile.feature1': 'iOS & Android Design',
    'services.mobile.feature2': 'Durchdachte User Journey',
    'services.mobile.feature3': 'Flüssiges Onboarding',
    'services.mobile.feature4': 'Icons, Menüs und alle kleinen Details die den Unterschied machen',
    'services.creative.title': 'Creative Direction',
    'services.creative.desc': 'Du hast die Ideen, aber willst dass alles ausgerichtet, sauber und kohärent ist? Ich übernehme das Steuer, du gibst mir die Richtung.',
    'services.creative.feature1': 'Art Direction',
    'services.creative.feature2': 'Kampagnenstrategie',
    'services.creative.feature3': 'Stylische aber nützliche Beratung',
    'services.creative.feature4': 'Globale Projektvision',
    'services.motion.title': 'Motion Design & Video',
    'services.motion.desc': 'Content der sich gut bewegt. Ich schneide, animiere, gebe deiner visuellen Kommunikation Rhythmus.',
    'services.motion.feature1': 'Stylische Logo-Animationen',
    'services.motion.feature2': 'Dynamische Videobearbeitung',
    'services.motion.feature3': 'Teaser, Trailer, Reels, Stories...',
    'services.motion.feature4': 'Micro-Animationen und smooth Effekte',
    'services.startProject': 'Projekt starten',

    // Testimonials Section
    'testimonials.subtitle': 'Kundenbewertungen',
    'testimonials.title': 'Was Kunden sagen',
    'testimonials.description': 'Feedback von Kunden, die mir ihre kreativen Projekte anvertraut haben.',
    'testimonials.trustedBy': 'Vertrauen mir',
    'testimonials.trustedByDesc': 'Unternehmen und Startups, die meine kreative Expertise gewählt haben',

    // Contact Section
    'contact.subtitle': 'Lass uns reden?',
    'contact.title1': 'Lass uns',
    'contact.title2': 'reden?',
    'contact.description': 'Hast du eine Idee? Brauchst du visuelle Hilfe? Oder willst einfach wissen ob es zwischen uns passen könnte?',
    'contact.getInTouch': 'Kontakt aufnehmen',
    'contact.getInTouchDesc': 'Schreib mir, ich antworte schnell (und immer gerne).',
    'contact.email': 'E-Mail',
    'contact.emailDesc': 'Für alle deine kreativen Projekte',
    'contact.phone': 'Telefon',
    'contact.phoneDesc': 'Verfügbar für dringende Projekte',
    'contact.location': 'Standort',
    'contact.locationDesc': 'Ansässig in der Genfersee-Region',
    'contact.followMe': 'Folge mir',
    'contact.sendMessage': 'Nachricht senden',
    'contact.name': 'Dein Name',
    'contact.namePlaceholder': 'Gib deinen Namen ein',
    'contact.emailPlaceholder': 'Gib deine E-Mail ein',
    'contact.subject': 'Betreff',
    'contact.subjectPlaceholder': 'Worum geht es?',
    'contact.message': 'Nachricht',
    'contact.messagePlaceholder': 'Erzähl mir von deinem Projekt...',
    'contact.sendBtn': 'Nachricht senden',

    // Footer
    'footer.description': 'Spezialist für kreative Lösungen aus der Schweiz. Ich verwandle deine Ideen in wirkungsvolle visuelle Erfahrungen.',
    'footer.quickLinks': 'Schnelle Links',
    'footer.services': 'Dienstleistungen',
    'footer.brandIdentity': 'Markenidentität',
    'footer.uiuxDesign': 'UI/UX Design',
    'footer.webDevelopment': 'Webentwicklung',
    'footer.motionGraphics': 'Motion Graphics',
    'footer.madeWith': 'Gemacht mit',
    'footer.inSwitzerland': 'in der Schweiz',
    'footer.allRights': '© 2024 Theo Blondel. Alle Rechte vorbehalten.'
  },
  it: {
    // Navigation
    'nav.about': 'Chi sono',
    'nav.work': 'Lavori',
    'nav.services': 'Servizi',
    'nav.contact': 'Contatti',
    'nav.letsTalk': 'Parliamone',

    // Hero Section
    'hero.subtitle': 'Soluzioni Creative',
    'hero.greeting': 'Ciao, sono Theo Blondel.',
    'hero.title1': 'Soluzioni',
    'hero.title2': 'Creative',
    'hero.description': 'Sono un mediamatico in Svizzera, e trasformo le tue idee in progetti visivi puliti, d\'impatto e davvero stilosi.',
    'hero.contactMe': 'Ne parliamo?',
    'hero.watchDemo': 'Guarda Demo',
    'hero.yearsExperience': 'Anni di Esperienza',
    'hero.projectsDelivered': 'Progetti Consegnati',
    'hero.clientSatisfaction': 'Soddisfazione Cliente',
    'hero.clientsWorldwide': 'Clienti nel Mondo',
    'hero.service1.title': 'Identità di Brand',
    'hero.service1.desc': 'Loghi professionali e identità visiva',
    'hero.service2.title': 'UI/UX Design',
    'hero.service2.desc': 'Interfacce intuitive e coinvolgenti',
    'hero.service3.title': 'Motion Graphics',
    'hero.service3.desc': 'Animazioni dinamiche e video',
    'hero.service4.title': 'Design Stampa',
    'hero.service4.desc': 'Materiali stampati professionali',

    // About Section
    'about.subtitle': 'Il Mio Percorso',
    'about.title1': 'Creativo nel profondo,',
    'about.title2': 'efficace nella forma.',
    'about.description1': 'Ho iniziato come molti: con montaggi YouTube a 15 anni, la testa nei pixel e negli effetti sonori. Minecraft, Fortnite, Call of... Ho passato ore a testare, smanettare, cercare cosa funziona.',
    'about.description2': 'Poi è arrivato il disegno. Poi la mediamatica. E lì ho capito: voglio fare questo. Creare. Progettare. Dare vita a idee visive che parlano alle persone.',
    'about.skill1.title': 'Adobe Creative Suite',
    'about.skill1.desc': 'Padronanza professionale della suite completa',
    'about.skill2.title': 'DaVinci Resolve',
    'about.skill2.desc': 'Montaggio video avanzato e color grading',
    'about.skill3.title': 'Autodesk Suite',
    'about.skill3.desc': 'Modellazione 3D e animazione',
    'about.skill4.title': 'Figma',
    'about.skill4.desc': 'UI/UX design e prototipazione',

    // Portfolio Section
    'portfolio.subtitle': 'I Miei Progetti',
    'portfolio.title1': 'Alcune cose',
    'portfolio.title2': 'che mi è piaciuto fare',
    'portfolio.description': 'Una selezione di progetti che mostrano il mio approccio creativo e la mia competenza tecnica.',
    'portfolio.category.all': 'Tutti',
    'portfolio.category.webApp': 'Web App',
    'portfolio.category.branding': 'Branding',
    'portfolio.category.mobile': 'Mobile',
    'portfolio.category.animation': 'Animazione',
    'portfolio.category.audio': 'Audio',
    'portfolio.viewAllBehance': 'Vedi tutto su Behance',

    // Services Section
    'services.subtitle': 'Cosa posso fare',
    'services.title': 'Cosa posso fare per te',
    'services.description': 'Soluzioni creative complete adattate alle tue esigenze e obiettivi.',
    'services.brandIdentity.title': 'Identità di Brand',
    'services.brandIdentity.desc': 'Hai bisogno di un logo che spacca e di un\'immagine che racconta chi sei? Ti aiuto a costruire una vera identità — non solo un logo fatto in fretta.',
    'services.brandIdentity.feature1': 'Logo professionale (non su Canva)',
    'services.brandIdentity.feature2': 'Linee guida del brand chiare',
    'services.brandIdentity.feature3': 'Identità visiva coerente',
    'services.brandIdentity.feature4': 'Posizionamento del brand solido',
    'services.uiux.title': 'UI/UX Design',
    'services.uiux.desc': 'Un buon design non è solo bello. Deve funzionare. Creo interfacce semplici, fluide e piacevoli da usare.',
    'services.uiux.feature1': 'Ricerca utente',
    'services.uiux.feature2': 'Wireframe puliti',
    'services.uiux.feature3': 'Mockup pixel-perfect',
    'services.uiux.feature4': 'Test per vedere se tutto regge',
    'services.webDev.title': 'Design Stampa',
    'services.webDev.desc': 'Roba che si può toccare. Volantini, biglietti, poster — tutto quello che si legge con gli occhi e le mani.',
    'services.webDev.feature1': 'Layout curato',
    'services.webDev.feature2': 'Buona scelta tipografica',
    'services.webDev.feature3': 'Armonie di colori perfette',
    'services.webDev.feature4': 'File pronti per la stampa',
    'services.mobile.title': 'Design Mobile',
    'services.mobile.desc': 'La tua app merita meglio di un template di default. Ti faccio un\'interfaccia chiara, intuitiva e piacevole da usare in metro.',
    'services.mobile.feature1': 'Design iOS e Android',
    'services.mobile.feature2': 'Percorso utente ben pensato',
    'services.mobile.feature3': 'Onboarding fluido',
    'services.mobile.feature4': 'Icone, menu e tutti i piccoli dettagli che fanno la differenza',
    'services.creative.title': 'Direzione Creativa',
    'services.creative.desc': 'Hai le idee, ma vuoi che tutto sia allineato, pulito e coerente? Prendo il volante, tu mi dai la direzione.',
    'services.creative.feature1': 'Direzione artistica',
    'services.creative.feature2': 'Strategia di campagna',
    'services.creative.feature3': 'Consigli stilosi ma utili',
    'services.creative.feature4': 'Visione globale del progetto',
    'services.motion.title': 'Motion Design e Video',
    'services.motion.desc': 'Contenuti che si muovono bene. Monto, animo, do ritmo alla tua comunicazione visiva.',
    'services.motion.feature1': 'Animazioni logo stilose',
    'services.motion.feature2': 'Montaggi video dinamici',
    'services.motion.feature3': 'Teaser, trailer, reel, stories...',
    'services.motion.feature4': 'Micro-animazioni ed effetti smooth',
    'services.startProject': 'Inizia un Progetto',

    // Testimonials Section
    'testimonials.subtitle': 'Recensioni Clienti',
    'testimonials.title': 'Cosa dicono i clienti',
    'testimonials.description': 'Feedback da clienti che mi hanno affidato i loro progetti creativi.',
    'testimonials.trustedBy': 'Si fidano di me',
    'testimonials.trustedByDesc': 'Aziende e startup che hanno scelto la mia competenza creativa',

    // Contact Section
    'contact.subtitle': 'Ne parliamo?',
    'contact.title1': 'Ne',
    'contact.title2': 'parliamo?',
    'contact.description': 'Hai un\'idea? Hai bisogno di aiuto visivo? O vuoi solo sapere se potremmo lavorare insieme?',
    'contact.getInTouch': 'Mettiamoci in Contatto',
    'contact.getInTouchDesc': 'Scrivimi, rispondo veloce (e sempre con piacere).',
    'contact.email': 'Email',
    'contact.emailDesc': 'Per tutti i tuoi progetti creativi',
    'contact.phone': 'Telefono',
    'contact.phoneDesc': 'Disponibile per progetti urgenti',
    'contact.location': 'Posizione',
    'contact.locationDesc': 'Basato nella regione del Lago Lemano',
    'contact.followMe': 'Seguimi',
    'contact.sendMessage': 'Invia un Messaggio',
    'contact.name': 'Il Tuo Nome',
    'contact.namePlaceholder': 'Inserisci il tuo nome',
    'contact.emailPlaceholder': 'Inserisci la tua email',
    'contact.subject': 'Oggetto',
    'contact.subjectPlaceholder': 'Di cosa si tratta?',
    'contact.message': 'Messaggio',
    'contact.messagePlaceholder': 'Parlami del tuo progetto...',
    'contact.sendBtn': 'Invia Messaggio',

    // Footer
    'footer.description': 'Specialista in soluzioni creative basato in Svizzera. Trasformo le tue idee in esperienze visive d\'impatto.',
    'footer.quickLinks': 'Link Rapidi',
    'footer.services': 'Servizi',
    'footer.brandIdentity': 'Identità di Brand',
    'footer.uiuxDesign': 'UI/UX Design',
    'footer.webDevelopment': 'Sviluppo Web',
    'footer.motionGraphics': 'Motion Graphics',
    'footer.madeWith': 'Fatto con',
    'footer.inSwitzerland': 'in Svizzera',
    'footer.allRights': '© 2024 Theo Blondel. Tutti i diritti riservati.'
  },
  pt: {
    // Navigation
    'nav.about': 'Sobre',
    'nav.work': 'Trabalhos',
    'nav.services': 'Serviços',
    'nav.contact': 'Contato',
    'nav.letsTalk': 'Vamos conversar',

    // Hero Section
    'hero.subtitle': 'Soluções Criativas',
    'hero.greeting': 'Oi, eu sou o Theo Blondel.',
    'hero.title1': 'Soluções',
    'hero.title2': 'Criativas',
    'hero.description': 'Sou um mediamaticista na Suíça, e transformo suas ideias em projetos visuais limpos, impactantes e realmente estilosos.',
    'hero.contactMe': 'Vamos conversar?',
    'hero.watchDemo': 'Ver Demo',
    'hero.yearsExperience': 'Anos de Experiência',
    'hero.projectsDelivered': 'Projetos Entregues',
    'hero.clientSatisfaction': 'Satisfação do Cliente',
    'hero.clientsWorldwide': 'Clientes no Mundo',
    'hero.service1.title': 'Identidade de Marca',
    'hero.service1.desc': 'Logos profissionais e identidade visual',
    'hero.service2.title': 'UI/UX Design',
    'hero.service2.desc': 'Interfaces intuitivas e envolventes',
    'hero.service3.title': 'Motion Graphics',
    'hero.service3.desc': 'Animações dinâmicas e vídeos',
    'hero.service4.title': 'Design Gráfico',
    'hero.service4.desc': 'Materiais impressos profissionais',

    // About Section
    'about.subtitle': 'Minha Jornada',
    'about.title1': 'Criativo no fundo,',
    'about.title2': 'eficiente na forma.',
    'about.description1': 'Comecei como muitos: com montagens do YouTube aos 15 anos, a cabeça nos pixels e efeitos sonoros. Minecraft, Fortnite, Call of... Passei horas testando, mexendo, procurando o que funciona.',
    'about.description2': 'Depois veio o desenho. Em seguida, a mediamática. E aí entendi: quero fazer isso. Criar. Projetar. Dar vida a ideias visuais que falam com as pessoas.',
    'about.skill1.title': 'Adobe Creative Suite',
    'about.skill1.desc': 'Domínio profissional da suíte completa',
    'about.skill2.title': 'DaVinci Resolve',
    'about.skill2.desc': 'Edição de vídeo avançada e correção de cor',
    'about.skill3.title': 'Autodesk Suite',
    'about.skill3.desc': 'Modelagem 3D e animação',
    'about.skill4.title': 'Figma',
    'about.skill4.desc': 'UI/UX design e prototipagem',

    // Portfolio Section
    'portfolio.subtitle': 'Meus Projetos',
    'portfolio.title1': 'Algumas coisas',
    'portfolio.title2': 'que adorei fazer',
    'portfolio.description': 'Uma seleção de projetos que mostram minha abordagem criativa e expertise técnica.',
    'portfolio.category.all': 'Todos',
    'portfolio.category.webApp': 'Web App',
    'portfolio.category.branding': 'Branding',
    'portfolio.category.mobile': 'Mobile',
    'portfolio.category.animation': 'Animação',
    'portfolio.category.audio': 'Áudio',
    'portfolio.viewAllBehance': 'Ver tudo no Behance',

    // Services Section
    'services.subtitle': 'O que posso fazer',
    'services.title': 'O que posso fazer por você',
    'services.description': 'Soluções criativas completas adaptadas às suas necessidades e objetivos.',
    'services.brandIdentity.title': 'Identidade de Marca',
    'services.brandIdentity.desc': 'Precisa de um logo que impressiona e uma imagem que conta quem você é? Te ajudo a construir uma identidade real — não apenas um logo rápido.',
    'services.brandIdentity.feature1': 'Logo profissional (não no Canva)',
    'services.brandIdentity.feature2': 'Manual da marca claro',
    'services.brandIdentity.feature3': 'Identidade visual coerente',
    'services.brandIdentity.feature4': 'Posicionamento de marca sólido',
    'services.uiux.title': 'UI/UX Design',
    'services.uiux.desc': 'Um bom design não é apenas bonito. Tem que funcionar. Crio interfaces simples, fluidas e agradáveis de usar.',
    'services.uiux.feature1': 'Pesquisa de usuário',
    'services.uiux.feature2': 'Wireframes limpos',
    'services.uiux.feature3': 'Mockups pixel-perfect',
    'services.uiux.feature4': 'Testes para ver se tudo funciona',
    'services.webDev.title': 'Design Gráfico',
    'services.webDev.desc': 'Coisas que você pode tocar. Panfletos, cartões, cartazes — tudo que se lê com os olhos e as mãos.',
    'services.webDev.feature1': 'Layout cuidadoso',
    'services.webDev.feature2': 'Boa escolha tipográfica',
    'services.webDev.feature3': 'Harmonias de cores perfeitas',
    'services.webDev.feature4': 'Arquivos prontos para impressão',
    'services.mobile.title': 'Design Mobile',
    'services.mobile.desc': 'Seu app merece melhor que um template padrão. Faço uma interface clara, intuitiva e agradável de usar no metrô.',
    'services.mobile.feature1': 'Design iOS e Android',
    'services.mobile.feature2': 'Jornada do usuário bem pensada',
    'services.mobile.feature3': 'Onboarding fluido',
    'services.mobile.feature4': 'Ícones, menus e todos os pequenos detalhes que fazem a diferença',
    'services.creative.title': 'Direção Criativa',
    'services.creative.desc': 'Você tem as ideias, mas quer que tudo esteja alinhado, limpo e coerente? Eu pego o volante, você me dá a direção.',
    'services.creative.feature1': 'Direção de arte',
    'services.creative.feature2': 'Estratégia de campanha',
    'services.creative.feature3': 'Conselhos estilosos mas úteis',
    'services.creative.feature4': 'Visão global do projeto',
    'services.motion.title': 'Motion Design e Vídeo',
    'services.motion.desc': 'Conteúdo que se move bem. Edito, animo, dou ritmo à sua comunicação visual.',
    'services.motion.feature1': 'Animações de logo estilosas',
    'services.motion.feature2': 'Edições de vídeo dinâmicas',
    'services.motion.feature3': 'Teasers, trailers, reels, stories...',
    'services.motion.feature4': 'Micro-animações e efeitos suaves',
    'services.startProject': 'Iniciar um Projeto',

    // Testimonials Section
    'testimonials.subtitle': 'Avaliações de Clientes',
    'testimonials.title': 'O que dizem os clientes',
    'testimonials.description': 'Feedback de clientes que confiaram em mim para seus projetos criativos.',
    'testimonials.trustedBy': 'Confiam em mim',
    'testimonials.trustedByDesc': 'Empresas e startups que escolheram minha expertise criativa',

    // Contact Section
    'contact.subtitle': 'Vamos conversar?',
    'contact.title1': 'Vamos',
    'contact.title2': 'conversar?',
    'contact.description': 'Tem uma ideia? Precisa de ajuda visual? Ou só quer saber se podemos trabalhar juntos?',
    'contact.getInTouch': 'Entrar em Contato',
    'contact.getInTouchDesc': 'Me escreva, respondo rápido (e sempre com prazer).',
    'contact.email': 'Email',
    'contact.emailDesc': 'Para todos os seus projetos criativos',
    'contact.phone': 'Telefone',
    'contact.phoneDesc': 'Disponível para projetos urgentes',
    'contact.location': 'Localização',
    'contact.locationDesc': 'Baseado na região do Lago Lemano',
    'contact.followMe': 'Me siga',
    'contact.sendMessage': 'Enviar uma Mensagem',
    'contact.name': 'Seu Nome',
    'contact.namePlaceholder': 'Digite seu nome',
    'contact.emailPlaceholder': 'Digite seu email',
    'contact.subject': 'Assunto',
    'contact.subjectPlaceholder': 'Sobre o que é?',
    'contact.message': 'Mensagem',
    'contact.messagePlaceholder': 'Me conte sobre seu projeto...',
    'contact.sendBtn': 'Enviar Mensagem',

    // Footer
    'footer.description': 'Especialista em soluções criativas baseado na Suíça. Transformo suas ideias em experiências visuais impactantes.',
    'footer.quickLinks': 'Links Rápidos',
    'footer.services': 'Serviços',
    'footer.brandIdentity': 'Identidade de Marca',
    'footer.uiuxDesign': 'UI/UX Design',
    'footer.webDevelopment': 'Desenvolvimento Web',
    'footer.motionGraphics': 'Motion Graphics',
    'footer.madeWith': 'Feito com',
    'footer.inSwitzerland': 'na Suíça',
    'footer.allRights': '© 2024 Theo Blondel. Todos os direitos reservados.'
  },
  sq: {
    // Navigation
    'nav.about': 'Rreth meje',
    'nav.work': 'Punët',
    'nav.services': 'Shërbimet',
    'nav.contact': 'Kontakti',
    'nav.letsTalk': 'Le të flasim',

    // Hero Section
    'hero.subtitle': 'Zgjidhje Kreative',
    'hero.greeting': 'Përshëndetje, unë jam Theo Blondel.',
    'hero.title1': 'Zgjidhje',
    'hero.title2': 'Kreative',
    'hero.description': 'Jam një mediamatik në Zvicër, dhe i transformoj idetë tuaja në projekte vizuale të pastra, me ndikim dhe vërtet stiloze.',
    'hero.contactMe': 'Le të flasim?',
    'hero.watchDemo': 'Shiko Demon',
    'hero.yearsExperience': 'Vite Përvojë',
    'hero.projectsDelivered': 'Projekte të Dorëzuara',
    'hero.clientSatisfaction': 'Kënaqësia e Klientit',
    'hero.clientsWorldwide': 'Klientë në Botë',
    'hero.service1.title': 'Identiteti i Markës',
    'hero.service1.desc': 'Logo profesionale dhe identitet vizual',
    'hero.service2.title': 'UI/UX Design',
    'hero.service2.desc': 'Ndërfaqe intuitive dhe tërheqëse',
    'hero.service3.title': 'Motion Graphics',
    'hero.service3.desc': 'Animacione dinamike dhe video',
    'hero.service4.title': 'Print Design',
    'hero.service4.desc': 'Materiale të shtypura profesionale',

    // About Section
    'about.subtitle': 'Rruga Ime',
    'about.title1': 'Kreativ në thelb,',
    'about.title2': 'efikas në formë.',
    'about.description1': 'Fillova si shumë të tjerë: me montazhe YouTube në moshën 15 vjeç, kokën në pixel dhe efekte zanore. Minecraft, Fortnite, Call of... Kalova orë duke testuar, eksperimentuar, duke kërkuar atë që funksionon.',
    'about.description2': 'Pastaj erdhi vizatimi. Më pas, mediamatikat. Dhe atje e kuptova: dua ta bëj këtë. Të krijoj. Të projektoj. T\'u jap jetë ideve vizuale që u flasin njerëzve.',
    'about.skill1.title': 'Adobe Creative Suite',
    'about.skill1.desc': 'Zotërim profesional i paketës së plotë',
    'about.skill2.title': 'DaVinci Resolve',
    'about.skill2.desc': 'Montim video i avancuar dhe korrigjim ngjyrash',
    'about.skill3.title': 'Autodesk Suite',
    'about.skill3.desc': 'Modelim 3D dhe animacion',
    'about.skill4.title': 'Figma',
    'about.skill4.desc': 'UI/UX design dhe prototipim',

    // Portfolio Section
    'portfolio.subtitle': 'Projektet e Mia',
    'portfolio.title1': 'Disa gjëra',
    'portfolio.title2': 'që më pëlqeu t\'i bëj',
    'portfolio.description': 'Një përzgjedhje projektesh që tregojnë qasjen time kreative dhe ekspertizën teknike.',
    'portfolio.category.all': 'Të gjitha',
    'portfolio.category.webApp': 'Web App',
    'portfolio.category.branding': 'Branding',
    'portfolio.category.mobile': 'Mobile',
    'portfolio.category.animation': 'Animacion',
    'portfolio.category.audio': 'Audio',
    'portfolio.viewAllBehance': 'Shiko të gjitha në Behance',

    // Services Section
    'services.subtitle': 'Çfarë mund të bëj',
    'services.title': 'Çfarë mund të bëj për ju',
    'services.description': 'Zgjidhje kreative të plota të përshtatura për nevojat dhe objektivat tuaja.',
    'services.brandIdentity.title': 'Identiteti i Markës',
    'services.brandIdentity.desc': 'Keni nevojë për një logo që bën përshtypje dhe një imazh që tregon se kush jeni? Ju ndihmoj të ndërtoni një identitet të vërtetë — jo vetëm një logo të shpejtë.',
    'services.brandIdentity.feature1': 'Logo profesionale (jo në Canva)',
    'services.brandIdentity.feature2': 'Udhëzime të qarta të markës',
    'services.brandIdentity.feature3': 'Identitet vizual i qëndrueshëm',
    'services.brandIdentity.feature4': 'Pozicionim i fortë i markës',
    'services.uiux.title': 'UI/UX Design',
    'services.uiux.desc': 'Një dizajn i mirë nuk është vetëm i bukur. Duhet të funksionojë. Krijoj ndërfaqe të thjeshta, të rrjedhshme dhe të këndshme për t\'u përdorur.',
    'services.uiux.feature1': 'Kërkimi i përdoruesit',
    'services.uiux.feature2': 'Wireframe të pastra',
    'services.uiux.feature3': 'Mockup pixel-perfect',
    'services.uiux.feature4': 'Teste për të parë nëse gjithçka funksionon',
    'services.webDev.title': 'Print Design',
    'services.webDev.desc': 'Gjëra që mund t\'i prekësh. Fletushka, karta, postera — gjithçka që lexohet me sy dhe duar.',
    'services.webDev.feature1': 'Layout i kujdesshëm',
    'services.webDev.feature2': 'Zgjedhje e mirë tipografike',
    'services.webDev.feature3': 'Harmoni të përsosura ngjyrash',
    'services.webDev.feature4': 'Skedarë të gatshëm për shtypje',
    'services.mobile.title': 'Mobile Design',
    'services.mobile.desc': 'Aplikacioni juaj meriton më shumë se një template i paracaktuar. Ju bëj një ndërfaqe të qartë, intuitive dhe të këndshme për t\'u përdorur në metro.',
    'services.mobile.feature1': 'Design iOS dhe Android',
    'services.mobile.feature2': 'Udhëtim i menduar mirë i përdoruesit',
    'services.mobile.feature3': 'Onboarding i rrjedhshëm',
    'services.mobile.feature4': 'Ikona, menu dhe të gjitha detajet e vogla që bëjnë ndryshimin',
    'services.creative.title': 'Drejtimi Kreativ',
    'services.creative.desc': 'Keni idetë, por doni që gjithçka të jetë e rreshtuar, e pastër dhe e qëndrueshme? Unë marr timonin, ju më jepni drejtimin.',
    'services.creative.feature1': 'Drejtimi artistik',
    'services.creative.feature2': 'Strategjia e fushatës',
    'services.creative.feature3': 'Këshilla stiloze por të dobishme',
    'services.creative.feature4': 'Vizioni global i projektit',
    'services.motion.title': 'Motion Design dhe Video',
    'services.motion.desc': 'Përmbajtje që lëviz mirë. Montoj, animoj, i jap ritëm komunikimit tuaj vizual.',
    'services.motion.feature1': 'Animacione logo stiloze',
    'services.motion.feature2': 'Montim video dinamik',
    'services.motion.feature3': 'Teaser, trailer, reel, stories...',
    'services.motion.feature4': 'Mikro-animacione dhe efekte të buta',
    'services.startProject': 'Fillo një Projekt',

    // Testimonials Section
    'testimonials.subtitle': 'Vlerësimet e Klientëve',
    'testimonials.title': 'Çfarë thonë klientët',
    'testimonials.description': 'Komente nga klientë që më besuan projektet e tyre kreative.',
    'testimonials.trustedBy': 'Më besojnë',
    'testimonials.trustedByDesc': 'Kompani dhe startup që zgjodhën ekspertizën time kreative',

    // Contact Section
    'contact.subtitle': 'Le të flasim?',
    'contact.title1': 'Le të',
    'contact.title2': 'flasim?',
    'contact.description': 'Keni një ide? Keni nevojë për ndihmë vizuale? Apo thjesht doni të dini nëse mund të punojmë së bashku?',
    'contact.getInTouch': 'Kontaktoni',
    'contact.getInTouchDesc': 'Më shkruani, përgjigjem shpejt (dhe gjithmonë me kënaqësi).',
    'contact.email': 'Email',
    'contact.emailDesc': 'Për të gjitha projektet tuaja kreative',
    'contact.phone': 'Telefon',
    'contact.phoneDesc': 'I disponueshëm për projekte urgjente',
    'contact.location': 'Vendndodhja',
    'contact.locationDesc': 'I bazuar në rajonin e Liqenit të Gjenevës',
    'contact.followMe': 'Më ndiqni',
    'contact.sendMessage': 'Dërgo një Mesazh',
    'contact.name': 'Emri Juaj',
    'contact.namePlaceholder': 'Shkruani emrin tuaj',
    'contact.emailPlaceholder': 'Shkruani email-in tuaj',
    'contact.subject': 'Subjekti',
    'contact.subjectPlaceholder': 'Për çfarë bëhet fjalë?',
    'contact.message': 'Mesazhi',
    'contact.messagePlaceholder': 'Më tregoni për projektin tuaj...',
    'contact.sendBtn': 'Dërgo Mesazhin',

    // Footer
    'footer.description': 'Specialist në zgjidhje kreative i bazuar në Zvicër. I transformoj idetë tuaja në përvojë vizuale me ndikim.',
    'footer.quickLinks': 'Lidhje të Shpejta',
    'footer.services': 'Shërbimet',
    'footer.brandIdentity': 'Identiteti i Markës',
    'footer.uiuxDesign': 'UI/UX Design',
    'footer.webDevelopment': 'Zhvillimi Web',
    'footer.motionGraphics': 'Motion Graphics',
    'footer.madeWith': 'Bërë me',
    'footer.inSwitzerland': 'në Zvicër',
    'footer.allRights': '© 2024 Theo Blondel. Të gjitha të drejtat e rezervuara.'
  }
};

interface AppProviderProps {
  children: ReactNode;
}

export function AppProvider({ children }: AppProviderProps) {
  const [theme, setTheme] = useState<Theme>('light');
  const [language, setLanguage] = useState<Language>('fr');

  useEffect(() => {
    const savedTheme = localStorage.getItem('theme') as Theme;
    const savedLanguage = localStorage.getItem('language') as Language;
    
    if (savedTheme) {
      setTheme(savedTheme);
    } else {
      const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
      setTheme(prefersDark ? 'dark' : 'light');
    }
    
    if (savedLanguage) {
      setLanguage(savedLanguage);
    } else {
      const browserLang = navigator.language.split('-')[0] as Language;
      if (Object.keys(translations).includes(browserLang)) {
        setLanguage(browserLang);
      }
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('theme', theme);
    if (theme === 'dark') {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [theme]);

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language === 'fr' ? 'fr' : language === 'en' ? 'en' : language;
  }, [language]);

  const toggleTheme = () => {
    setTheme(prev => prev === 'light' ? 'dark' : 'light');
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  const value: AppContextType = {
    theme,
    language,
    toggleTheme,
    setLanguage,
    t
  };

  return (
    <AppContext.Provider value={value}>
      {children}
    </AppContext.Provider>
  );
}

export function useApp() {
  const context = useContext(AppContext);
  if (context === undefined) {
    throw new Error('useApp must be used within an AppProvider');
  }
  return context;
}