import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Theme = 'light' | 'dark';
type Language = 'en' | 'fr' | 'es' | 'ru' | 'zh' | 'ja' | 'de' | 'it' | 'pt' | 'sq';

interface AppContextType {
  theme: Theme;
  language: Language;
  toggleTheme: () => void;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const AppContext = createContext<AppContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.about': 'About',
    'nav.work': 'Work',
    'nav.services': 'Services',
    'nav.contact': 'Contact',
    'nav.letsTalk': "Let's Talk",

    // Hero Section
    'hero.subtitle': 'Creative Designer & Brand Strategist',
    'hero.greeting': 'Hello, I am Theo Blondel',
    'hero.title1': 'Creative',
    'hero.title2': 'Designer',
    'hero.title3': 'Professional',
    'hero.description': 'Specialized in brand identity and visual design. I create authentic visual experiences and memorable brand identities that tell your story.',
    'hero.contactMe': 'Contact Me',
    'hero.watchDemo': 'Watch Demo',
    'hero.yearsExperience': 'Years Experience',
    'hero.projectsDelivered': 'Projects Delivered',
    'hero.clientSatisfaction': 'Client Satisfaction',
    'hero.clientsWorldwide': 'Clients Worldwide',
    'hero.service1.title': 'Brand Identity',
    'hero.service1.desc': 'Logo design and complete visual identity systems',
    'hero.service2.title': 'Graphic Design',
    'hero.service2.desc': 'Print and digital design solutions',
    'hero.service3.title': 'Marketing Design',
    'hero.service3.desc': 'Creative campaigns and marketing materials',
    'hero.service4.title': 'Motion Graphics',
    'hero.service4.desc': 'Animated content and visual storytelling',

    // About Section
    'about.subtitle': 'About Me',
    'about.title1': 'Passionate',
    'about.title2': 'Creative',
    'about.title3': 'Professional',
    'about.description1': 'With over 5 years of experience in creative design, I specialize in brand identity and visual storytelling. My approach combines strategic thinking with creative execution to deliver impactful design solutions.',
    'about.description2': 'I believe in the power of authentic visual communication to transform brands and create meaningful connections with audiences.',
    'about.skill1.title': 'Brand Identity',
    'about.skill1.desc': 'Logo design, visual identity systems, brand guidelines',
    'about.skill2.title': 'Graphic Design',
    'about.skill2.desc': 'Print design, digital graphics, marketing materials',
    'about.skill3.title': 'Motion Graphics',
    'about.skill3.desc': 'Animation, video editing, visual effects',
    'about.skill4.title': 'Creative Strategy',
    'about.skill4.desc': 'Brand positioning, creative direction, campaign strategy',

    // Portfolio Section
    'portfolio.subtitle': 'My Work',
    'portfolio.title1': 'Featured',
    'portfolio.title2': 'Creative',
    'portfolio.title3': 'Projects',
    'portfolio.description': 'Discover a selection of my creative projects, from brand identities to marketing campaigns.',
    'portfolio.category.all': 'All Projects',
    'portfolio.category.webApp': 'Digital Design',
    'portfolio.category.branding': 'Branding',
    'portfolio.category.mobile': 'Mobile Design',
    'portfolio.category.animation': 'Animation',
    'portfolio.category.audio': 'Creative Experience',
    'portfolio.viewAllBehance': 'View All on Behance',

    // Services Section
    'services.subtitle': 'Services',
    'services.title': 'Creative Solutions',
    'services.description': 'I offer comprehensive creative services to help your brand stand out and connect with your audience.',
    'services.brandIdentity.title': 'Brand Identity',
    'services.brandIdentity.desc': 'Complete brand identity systems including logo design, visual guidelines, and brand strategy.',
    'services.uiux.title': 'Graphic Design',
    'services.uiux.desc': 'Print and digital design solutions for marketing materials, publications, and campaigns.',
    'services.webDev.title': 'Print Design',
    'services.webDev.desc': 'Professional print design for brochures, posters, packaging, and corporate materials.',
    'services.mobile.title': 'Marketing Design',
    'services.mobile.desc': 'Creative marketing materials and campaign design to promote your brand effectively.',
    'services.motion.title': 'Motion Graphics',
    'services.motion.desc': 'Animated content, video editing, and motion graphics for digital campaigns.',
    'services.creative.title': 'Creative Direction',
    'services.creative.desc': 'Strategic creative direction and art direction for comprehensive brand campaigns.',
    'services.startProject': 'Start a Project',

    // Testimonials Section
    'testimonials.subtitle': 'Testimonials',
    'testimonials.title': 'Client Feedback',
    'testimonials.description': 'What my clients say about working with me and the results we achieved together.',
    'testimonials.trustedBy': 'Trusted by Creative Brands',
    'testimonials.trustedByDesc': 'I have had the privilege of working with amazing brands and creative agencies.',

    // Contact Section
    'contact.subtitle': 'Contact',
    'contact.title1': "Let's",
    'contact.title2': 'Create',
    'contact.title3': 'Together',
    'contact.description': 'Ready to bring your creative vision to life? Let\'s discuss your project and create something amazing together.',
    'contact.getInTouch': 'Get in Touch',
    'contact.getInTouchDesc': 'I\'m always excited to work on new creative projects.',
    'contact.email': 'Email',
    'contact.emailDesc': 'Send me a message',
    'contact.phone': 'Phone',
    'contact.phoneDesc': 'Call me directly',
    'contact.location': 'Location',
    'contact.locationDesc': 'Based in Switzerland',
    'contact.followMe': 'Follow Me',
    'contact.sendMessage': 'Send a Message',
    'contact.name': 'Name',
    'contact.namePlaceholder': 'Your name',
    'contact.emailPlaceholder': 'your.email@example.com',
    'contact.subject': 'Subject',
    'contact.subjectPlaceholder': 'Project subject',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Tell me about your project...',
    'contact.sendBtn': 'Send Message',

    // Footer
    'footer.description': 'Creative designer specialized in brand identity and visual storytelling. Creating authentic experiences that connect brands with their audience.',
    'footer.quickLinks': 'Quick Links',
    'footer.services': 'Services',
    'footer.brandIdentity': 'Brand Identity',
    'footer.uiuxDesign': 'Graphic Design',
    'footer.webDevelopment': 'Print Design',
    'footer.motionGraphics': 'Motion Graphics',
    'footer.madeWith': 'Made with',
    'footer.inSwitzerland': 'in Switzerland',
    'footer.allRights': '© 2024 Theo Blondel. All rights reserved.'
  },
  fr: {
    // Navigation
    'nav.about': 'À Propos',
    'nav.work': 'Projets',
    'nav.services': 'Services',
    'nav.contact': 'Contact',
    'nav.letsTalk': 'Discutons',

    // Hero Section
    'hero.subtitle': 'Designer Créatif & Stratège de Marque',
    'hero.greeting': 'Bonjour, je suis Theo Blondel',
    'hero.title1': 'Designer',
    'hero.title2': 'Créatif',
    'hero.title3': 'Professionnel',
    'hero.description': 'Spécialisé en identité de marque et design visuel. Je crée des expériences visuelles authentiques et des identités de marque mémorables qui racontent votre histoire.',
    'hero.contactMe': 'Me Contacter',
    'hero.watchDemo': 'Voir Démo',
    'hero.yearsExperience': "Années d'Expérience",
    'hero.projectsDelivered': 'Projets Réalisés',
    'hero.clientSatisfaction': 'Satisfaction Client',
    'hero.clientsWorldwide': 'Clients Internationaux',
    'hero.service1.title': 'Identité de Marque',
    'hero.service1.desc': 'Création de logos et systèmes d\'identité visuelle complets',
    'hero.service2.title': 'Design Graphique',
    'hero.service2.desc': 'Solutions de design print et digital',
    'hero.service3.title': 'Design Marketing',
    'hero.service3.desc': 'Campagnes créatives et supports marketing',
    'hero.service4.title': 'Motion Graphics',
    'hero.service4.desc': 'Contenu animé et storytelling visuel',

    // About Section
    'about.subtitle': 'À Propos',
    'about.title1': 'Créatif',
    'about.title2': 'Passionné',
    'about.title3': 'Professionnel',
    'about.description1': 'Avec plus de 5 ans d\'expérience en design créatif, je me spécialise dans l\'identité de marque et le storytelling visuel. Mon approche combine réflexion stratégique et exécution créative pour livrer des solutions design impactantes.',
    'about.description2': 'Je crois au pouvoir de la communication visuelle authentique pour transformer les marques et créer des connexions significatives avec les audiences.',
    'about.skill1.title': 'Identité de Marque',
    'about.skill1.desc': 'Création de logos, systèmes d\'identité visuelle, chartes graphiques',
    'about.skill2.title': 'Design Graphique',
    'about.skill2.desc': 'Design print, graphiques digitaux, supports marketing',
    'about.skill3.title': 'Motion Graphics',
    'about.skill3.desc': 'Animation, montage vidéo, effets visuels',
    'about.skill4.title': 'Stratégie Créative',
    'about.skill4.desc': 'Positionnement de marque, direction créative, stratégie de campagne',

    // Portfolio Section
    'portfolio.subtitle': 'Mes Projets',
    'portfolio.title1': 'Projets',
    'portfolio.title2': 'Créatifs',
    'portfolio.title3': 'Sélectionnés',
    'portfolio.description': 'Découvrez une sélection de mes projets créatifs, des identités de marque aux campagnes marketing.',
    'portfolio.category.all': 'Tous les Projets',
    'portfolio.category.webApp': 'Design Digital',
    'portfolio.category.branding': 'Branding',
    'portfolio.category.mobile': 'Design Mobile',
    'portfolio.category.animation': 'Animation',
    'portfolio.category.audio': 'Expérience Créative',
    'portfolio.viewAllBehance': 'Voir Tout sur Behance',

    // Services Section
    'services.subtitle': 'Services',
    'services.title': 'Solutions Créatives',
    'services.description': 'J\'offre des services créatifs complets pour aider votre marque à se démarquer et connecter avec votre audience.',
    'services.brandIdentity.title': 'Identité de Marque',
    'services.brandIdentity.desc': 'Systèmes d\'identité de marque complets incluant création de logo, chartes visuelles et stratégie de marque.',
    'services.uiux.title': 'Design Graphique',
    'services.uiux.desc': 'Solutions de design print et digital pour supports marketing, publications et campagnes.',
    'services.webDev.title': 'Design Print',
    'services.webDev.desc': 'Design print professionnel pour brochures, affiches, packaging et supports corporate.',
    'services.mobile.title': 'Design Marketing',
    'services.mobile.desc': 'Supports marketing créatifs et design de campagnes pour promouvoir efficacement votre marque.',
    'services.motion.title': 'Motion Graphics',
    'services.motion.desc': 'Contenu animé, montage vidéo et motion graphics pour campagnes digitales.',
    'services.creative.title': 'Direction Créative',
    'services.creative.desc': 'Direction créative stratégique et direction artistique pour campagnes de marque complètes.',
    'services.startProject': 'Démarrer un Projet',

    // Testimonials Section
    'testimonials.subtitle': 'Témoignages',
    'testimonials.title': 'Retours Clients',
    'testimonials.description': 'Ce que mes clients disent de notre collaboration et des résultats que nous avons obtenus ensemble.',
    'testimonials.trustedBy': 'Fait Confiance par des Marques Créatives',
    'testimonials.trustedByDesc': 'J\'ai eu le privilège de travailler avec des marques et agences créatives exceptionnelles.',

    // Contact Section
    'contact.subtitle': 'Contact',
    'contact.title1': 'Créons',
    'contact.title2': 'Quelque',
    'contact.title3': 'Chose',
    'contact.description': 'Prêt à donner vie à votre vision créative ? Discutons de votre projet et créons quelque chose d\'extraordinaire ensemble.',
    'contact.getInTouch': 'Prenons Contact',
    'contact.getInTouchDesc': 'Je suis toujours enthousiaste à l\'idée de travailler sur de nouveaux projets créatifs.',
    'contact.email': 'Email',
    'contact.emailDesc': 'Envoyez-moi un message',
    'contact.phone': 'Téléphone',
    'contact.phoneDesc': 'Appelez-moi directement',
    'contact.location': 'Localisation',
    'contact.locationDesc': 'Basé en Suisse',
    'contact.followMe': 'Suivez-moi',
    'contact.sendMessage': 'Envoyer un Message',
    'contact.name': 'Nom',
    'contact.namePlaceholder': 'Votre nom',
    'contact.emailPlaceholder': 'votre.email@exemple.com',
    'contact.subject': 'Sujet',
    'contact.subjectPlaceholder': 'Sujet du projet',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Parlez-moi de votre projet...',
    'contact.sendBtn': 'Envoyer le Message',

    // Footer
    'footer.description': 'Designer créatif spécialisé en identité de marque et storytelling visuel. Création d\'expériences authentiques qui connectent les marques à leur audience.',
    'footer.quickLinks': 'Liens Rapides',
    'footer.services': 'Services',
    'footer.brandIdentity': 'Identité de Marque',
    'footer.uiuxDesign': 'Design Graphique',
    'footer.webDevelopment': 'Design Print',
    'footer.motionGraphics': 'Motion Graphics',
    'footer.madeWith': 'Fait avec',
    'footer.inSwitzerland': 'en Suisse',
    'footer.allRights': '© 2024 Theo Blondel. Tous droits réservés.'
  },
  es: {
    // Navigation
    'nav.about': 'Acerca',
    'nav.work': 'Trabajo',
    'nav.services': 'Servicios',
    'nav.contact': 'Contacto',
    'nav.letsTalk': 'Hablemos',

    // Hero Section
    'hero.subtitle': 'Diseñador Creativo y Estratega de Marca',
    'hero.greeting': 'Hola, soy Theo Blondel',
    'hero.title1': 'Diseñador',
    'hero.title2': 'Creativo',
    'hero.title3': 'Profesional',
    'hero.description': 'Especializado en identidad de marca y diseño visual. Creo experiencias visuales auténticas e identidades de marca memorables que cuentan tu historia.',
    'hero.contactMe': 'Contáctame',
    'hero.watchDemo': 'Ver Demo',
    'hero.yearsExperience': 'Años de Experiencia',
    'hero.projectsDelivered': 'Proyectos Entregados',
    'hero.clientSatisfaction': 'Satisfacción del Cliente',
    'hero.clientsWorldwide': 'Clientes Mundiales',
    'hero.service1.title': 'Identidad de Marca',
    'hero.service1.desc': 'Diseño de logos y sistemas de identidad visual completos',
    'hero.service2.title': 'Diseño Gráfico',
    'hero.service2.desc': 'Soluciones de diseño impreso y digital',
    'hero.service3.title': 'Diseño de Marketing',
    'hero.service3.desc': 'Campañas creativas y materiales de marketing',
    'hero.service4.title': 'Motion Graphics',
    'hero.service4.desc': 'Contenido animado y narrativa visual',

    // About Section
    'about.subtitle': 'Acerca de Mí',
    'about.title1': 'Creativo',
    'about.title2': 'Apasionado',
    'about.title3': 'Profesional',
    'about.description1': 'Con más de 5 años de experiencia en diseño creativo, me especializo en identidad de marca y narrativa visual. Mi enfoque combina pensamiento estratégico con ejecución creativa para entregar soluciones de diseño impactantes.',
    'about.description2': 'Creo en el poder de la comunicación visual auténtica para transformar marcas y crear conexiones significativas con las audiencias.',
    'about.skill1.title': 'Identidad de Marca',
    'about.skill1.desc': 'Diseño de logos, sistemas de identidad visual, guías de marca',
    'about.skill2.title': 'Diseño Gráfico',
    'about.skill2.desc': 'Diseño impreso, gráficos digitales, materiales de marketing',
    'about.skill3.title': 'Motion Graphics',
    'about.skill3.desc': 'Animación, edición de video, efectos visuales',
    'about.skill4.title': 'Estrategia Creativa',
    'about.skill4.desc': 'Posicionamiento de marca, dirección creativa, estrategia de campaña',

    // Portfolio Section
    'portfolio.subtitle': 'Mi Trabajo',
    'portfolio.title1': 'Proyectos',
    'portfolio.title2': 'Creativos',
    'portfolio.title3': 'Destacados',
    'portfolio.description': 'Descubre una selección de mis proyectos creativos, desde identidades de marca hasta campañas de marketing.',
    'portfolio.category.all': 'Todos los Proyectos',
    'portfolio.category.webApp': 'Diseño Digital',
    'portfolio.category.branding': 'Branding',
    'portfolio.category.mobile': 'Diseño Móvil',
    'portfolio.category.animation': 'Animación',
    'portfolio.category.audio': 'Experiencia Creativa',
    'portfolio.viewAllBehance': 'Ver Todo en Behance',

    // Services Section
    'services.subtitle': 'Servicios',
    'services.title': 'Soluciones Creativas',
    'services.description': 'Ofrezco servicios creativos integrales para ayudar a tu marca a destacar y conectar con tu audiencia.',
    'services.brandIdentity.title': 'Identidad de Marca',
    'services.brandIdentity.desc': 'Sistemas completos de identidad de marca incluyendo diseño de logo, guías visuales y estrategia de marca.',
    'services.uiux.title': 'Diseño Gráfico',
    'services.uiux.desc': 'Soluciones de diseño impreso y digital para materiales de marketing, publicaciones y campañas.',
    'services.webDev.title': 'Diseño Impreso',
    'services.webDev.desc': 'Diseño impreso profesional para folletos, carteles, packaging y materiales corporativos.',
    'services.mobile.title': 'Diseño de Marketing',
    'services.mobile.desc': 'Materiales de marketing creativos y diseño de campañas para promover tu marca efectivamente.',
    'services.motion.title': 'Motion Graphics',
    'services.motion.desc': 'Contenido animado, edición de video y motion graphics para campañas digitales.',
    'services.creative.title': 'Dirección Creativa',
    'services.creative.desc': 'Dirección creativa estratégica y dirección artística para campañas de marca integrales.',
    'services.startProject': 'Iniciar un Proyecto',

    // Testimonials Section
    'testimonials.subtitle': 'Testimonios',
    'testimonials.title': 'Comentarios de Clientes',
    'testimonials.description': 'Lo que mis clientes dicen sobre trabajar conmigo y los resultados que logramos juntos.',
    'testimonials.trustedBy': 'Confiado por Marcas Creativas',
    'testimonials.trustedByDesc': 'He tenido el privilegio de trabajar con marcas y agencias creativas increíbles.',

    // Contact Section
    'contact.subtitle': 'Contacto',
    'contact.title1': 'Creemos',
    'contact.title2': 'Algo',
    'contact.title3': 'Juntos',
    'contact.description': '¿Listo para dar vida a tu visión creativa? Hablemos de tu proyecto y creemos algo increíble juntos.',
    'contact.getInTouch': 'Ponte en Contacto',
    'contact.getInTouchDesc': 'Siempre estoy emocionado de trabajar en nuevos proyectos creativos.',
    'contact.email': 'Email',
    'contact.emailDesc': 'Envíame un mensaje',
    'contact.phone': 'Teléfono',
    'contact.phoneDesc': 'Llámame directamente',
    'contact.location': 'Ubicación',
    'contact.locationDesc': 'Basado en Suiza',
    'contact.followMe': 'Sígueme',
    'contact.sendMessage': 'Enviar un Mensaje',
    'contact.name': 'Nombre',
    'contact.namePlaceholder': 'Tu nombre',
    'contact.emailPlaceholder': 'tu.email@ejemplo.com',
    'contact.subject': 'Asunto',
    'contact.subjectPlaceholder': 'Asunto del proyecto',
    'contact.message': 'Mensaje',
    'contact.messagePlaceholder': 'Cuéntame sobre tu proyecto...',
    'contact.sendBtn': 'Enviar Mensaje',

    // Footer
    'footer.description': 'Diseñador creativo especializado en identidad de marca y narrativa visual. Creando experiencias auténticas que conectan marcas con su audiencia.',
    'footer.quickLinks': 'Enlaces Rápidos',
    'footer.services': 'Servicios',
    'footer.brandIdentity': 'Identidad de Marca',
    'footer.uiuxDesign': 'Diseño Gráfico',
    'footer.webDevelopment': 'Diseño Impreso',
    'footer.motionGraphics': 'Motion Graphics',
    'footer.madeWith': 'Hecho con',
    'footer.inSwitzerland': 'en Suiza',
    'footer.allRights': '© 2024 Theo Blondel. Todos los derechos reservados.'
  },
  ru: {
    // Navigation
    'nav.about': 'О нас',
    'nav.work': 'Работы',
    'nav.services': 'Услуги',
    'nav.contact': 'Контакты',
    'nav.letsTalk': 'Поговорим',

    // Hero Section
    'hero.subtitle': 'Креативный Дизайнер и Бренд-Стратег',
    'hero.greeting': 'Привет, я Тео Блондель',
    'hero.title1': 'Креативный',
    'hero.title2': 'Дизайнер',
    'hero.title3': 'Профессионал',
    'hero.description': 'Специализируюсь на брендинге и визуальном дизайне. Создаю аутентичные визуальные впечатления и запоминающиеся фирменные стили, которые рассказывают вашу историю.',
    'hero.contactMe': 'Связаться',
    'hero.watchDemo': 'Смотреть Демо',
    'hero.yearsExperience': 'Лет Опыта',
    'hero.projectsDelivered': 'Проектов Выполнено',
    'hero.clientSatisfaction': 'Удовлетворенность Клиентов',
    'hero.clientsWorldwide': 'Клиентов по Всему Миру',
    'hero.service1.title': 'Фирменный Стиль',
    'hero.service1.desc': 'Дизайн логотипов и полные системы визуальной идентичности',
    'hero.service2.title': 'Графический Дизайн',
    'hero.service2.desc': 'Решения для печатного и цифрового дизайна',
    'hero.service3.title': 'Маркетинговый Дизайн',
    'hero.service3.desc': 'Креативные кампании и маркетинговые материалы',
    'hero.service4.title': 'Моушн Графика',
    'hero.service4.desc': 'Анимированный контент и визуальное повествование',

    // About Section
    'about.subtitle': 'Обо Мне',
    'about.title1': 'Страстный',
    'about.title2': 'Креативный',
    'about.title3': 'Профессионал',
    'about.description1': 'С более чем 5-летним опытом в креативном дизайне, я специализируюсь на брендинге и визуальном повествовании. Мой подход сочетает стратегическое мышление с креативным исполнением для создания впечатляющих дизайнерских решений.',
    'about.description2': 'Я верю в силу аутентичной визуальной коммуникации для трансформации брендов и создания значимых связей с аудиторией.',
    'about.skill1.title': 'Фирменный Стиль',
    'about.skill1.desc': 'Дизайн логотипов, системы визуальной идентичности, брендбуки',
    'about.skill2.title': 'Графический Дизайн',
    'about.skill2.desc': 'Печатный дизайн, цифровая графика, маркетинговые материалы',
    'about.skill3.title': 'Моушн Графика',
    'about.skill3.desc': 'Анимация, видеомонтаж, визуальные эффекты',
    'about.skill4.title': 'Креативная Стратегия',
    'about.skill4.desc': 'Позиционирование бренда, креативное руководство, стратегия кампаний',

    // Portfolio Section
    'portfolio.subtitle': 'Мои Работы',
    'portfolio.title1': 'Избранные',
    'portfolio.title2': 'Креативные',
    'portfolio.title3': 'Проекты',
    'portfolio.description': 'Откройте для себя подборку моих креативных проектов, от фирменных стилей до маркетинговых кампаний.',
    'portfolio.category.all': 'Все Проекты',
    'portfolio.category.webApp': 'Цифровой Дизайн',
    'portfolio.category.branding': 'Брендинг',
    'portfolio.category.mobile': 'Мобильный Дизайн',
    'portfolio.category.animation': 'Анимация',
    'portfolio.category.audio': 'Креативный Опыт',
    'portfolio.viewAllBehance': 'Смотреть Все на Behance',

    // Services Section
    'services.subtitle': 'Услуги',
    'services.title': 'Креативные Решения',
    'services.description': 'Я предлагаю комплексные креативные услуги, чтобы помочь вашему бренду выделиться и связаться с вашей аудиторией.',
    'services.brandIdentity.title': 'Фирменный Стиль',
    'services.brandIdentity.desc': 'Полные системы фирменного стиля, включая дизайн логотипа, визуальные руководства и стратегию бренда.',
    'services.uiux.title': 'Графический Дизайн',
    'services.uiux.desc': 'Решения для печатного и цифрового дизайна для маркетинговых материалов, публикаций и кампаний.',
    'services.webDev.title': 'Печатный Дизайн',
    'services.webDev.desc': 'Профессиональный печатный дизайн для брошюр, плакатов, упаковки и корпоративных материалов.',
    'services.mobile.title': 'Маркетинговый Дизайн',
    'services.mobile.desc': 'Креативные маркетинговые материалы и дизайн кампаний для эффективного продвижения вашего бренда.',
    'services.motion.title': 'Моушн Графика',
    'services.motion.desc': 'Анимированный контент, видеомонтаж и моушн графика для цифровых кампаний.',
    'services.creative.title': 'Креативное Руководство',
    'services.creative.desc': 'Стратегическое креативное руководство и арт-дирекция для комплексных брендовых кампаний.',
    'services.startProject': 'Начать Проект',

    // Testimonials Section
    'testimonials.subtitle': 'Отзывы',
    'testimonials.title': 'Отзывы Клиентов',
    'testimonials.description': 'Что мои клиенты говорят о работе со мной и результатах, которых мы достигли вместе.',
    'testimonials.trustedBy': 'Доверяют Креативные Бренды',
    'testimonials.trustedByDesc': 'У меня была привилегия работать с удивительными брендами и креативными агентствами.',

    // Contact Section
    'contact.subtitle': 'Контакты',
    'contact.title1': 'Давайте',
    'contact.title2': 'Создадим',
    'contact.title3': 'Вместе',
    'contact.description': 'Готовы воплотить ваше креативное видение в жизнь? Давайте обсудим ваш проект и создадим что-то удивительное вместе.',
    'contact.getInTouch': 'Связаться',
    'contact.getInTouchDesc': 'Я всегда рад работать над новыми креативными проектами.',
    'contact.email': 'Email',
    'contact.emailDesc': 'Отправьте мне сообщение',
    'contact.phone': 'Телефон',
    'contact.phoneDesc': 'Позвоните мне напрямую',
    'contact.location': 'Местоположение',
    'contact.locationDesc': 'Базируюсь в Швейцарии',
    'contact.followMe': 'Подписывайтесь',
    'contact.sendMessage': 'Отправить Сообщение',
    'contact.name': 'Имя',
    'contact.namePlaceholder': 'Ваше имя',
    'contact.emailPlaceholder': 'ваш.email@пример.com',
    'contact.subject': 'Тема',
    'contact.subjectPlaceholder': 'Тема проекта',
    'contact.message': 'Сообщение',
    'contact.messagePlaceholder': 'Расскажите мне о вашем проекте...',
    'contact.sendBtn': 'Отправить Сообщение',

    // Footer
    'footer.description': 'Креативный дизайнер, специализирующийся на брендинге и визуальном повествовании. Создание аутентичных впечатлений, которые связывают бренды с их аудиторией.',
    'footer.quickLinks': 'Быстрые Ссылки',
    'footer.services': 'Услуги',
    'footer.brandIdentity': 'Фирменный Стиль',
    'footer.uiuxDesign': 'Графический Дизайн',
    'footer.webDevelopment': 'Печатный Дизайн',
    'footer.motionGraphics': 'Моушн Графика',
    'footer.madeWith': 'Сделано с',
    'footer.inSwitzerland': 'в Швейцарии',
    'footer.allRights': '© 2024 Тео Блондель. Все права защищены.'
  },
  zh: {
    // Navigation
    'nav.about': '关于',
    'nav.work': '作品',
    'nav.services': '服务',
    'nav.contact': '联系',
    'nav.letsTalk': '让我们聊聊',

    // Hero Section
    'hero.subtitle': '创意设计师和品牌策略师',
    'hero.greeting': '你好，我是Theo Blondel',
    'hero.title1': '创意',
    'hero.title2': '设计师',
    'hero.title3': '专业人士',
    'hero.description': '专注于品牌识别和视觉设计。我创造真实的视觉体验和令人难忘的品牌形象，讲述您的故事。',
    'hero.contactMe': '联系我',
    'hero.watchDemo': '观看演示',
    'hero.yearsExperience': '年经验',
    'hero.projectsDelivered': '项目交付',
    'hero.clientSatisfaction': '客户满意度',
    'hero.clientsWorldwide': '全球客户',
    'hero.service1.title': '品牌识别',
    'hero.service1.desc': '标志设计和完整的视觉识别系统',
    'hero.service2.title': '平面设计',
    'hero.service2.desc': '印刷和数字设计解决方案',
    'hero.service3.title': '营销设计',
    'hero.service3.desc': '创意活动和营销材料',
    'hero.service4.title': '动态图形',
    'hero.service4.desc': '动画内容和视觉叙事',

    // About Section
    'about.subtitle': '关于我',
    'about.title1': '充满激情的',
    'about.title2': '创意',
    'about.title3': '专业人士',
    'about.description1': '拥有超过5年的创意设计经验，我专注于品牌识别和视觉叙事。我的方法结合了战略思维和创意执行，提供有影响力的设计解决方案。',
    'about.description2': '我相信真实视觉传达的力量能够转变品牌并与受众建立有意义的联系。',
    'about.skill1.title': '品牌识别',
    'about.skill1.desc': '标志设计、视觉识别系统、品牌指南',
    'about.skill2.title': '平面设计',
    'about.skill2.desc': '印刷设计、数字图形、营销材料',
    'about.skill3.title': '动态图形',
    'about.skill3.desc': '动画、视频编辑、视觉效果',
    'about.skill4.title': '创意策略',
    'about.skill4.desc': '品牌定位、创意指导、活动策略',

    // Portfolio Section
    'portfolio.subtitle': '我的作品',
    'portfolio.title1': '精选',
    'portfolio.title2': '创意',
    'portfolio.title3': '项目',
    'portfolio.description': '发现我的创意项目精选，从品牌识别到营销活动。',
    'portfolio.category.all': '所有项目',
    'portfolio.category.webApp': '数字设计',
    'portfolio.category.branding': '品牌设计',
    'portfolio.category.mobile': '移动设计',
    'portfolio.category.animation': '动画',
    'portfolio.category.audio': '创意体验',
    'portfolio.viewAllBehance': '在Behance查看全部',

    // Services Section
    'services.subtitle': '服务',
    'services.title': '创意解决方案',
    'services.description': '我提供全面的创意服务，帮助您的品牌脱颖而出并与您的受众建立联系。',
    'services.brandIdentity.title': '品牌识别',
    'services.brandIdentity.desc': '完整的品牌识别系统，包括标志设计、视觉指南和品牌策略。',
    'services.uiux.title': '平面设计',
    'services.uiux.desc': '营销材料、出版物和活动的印刷和数字设计解决方案。',
    'services.webDev.title': '印刷设计',
    'services.webDev.desc': '专业的印刷设计，包括宣传册、海报、包装和企业材料。',
    'services.mobile.title': '营销设计',
    'services.mobile.desc': '创意营销材料和活动设计，有效推广您的品牌。',
    'services.motion.title': '动态图形',
    'services.motion.desc': '数字活动的动画内容、视频编辑和动态图形。',
    'services.creative.title': '创意指导',
    'services.creative.desc': '综合品牌活动的战略创意指导和艺术指导。',
    'services.startProject': '开始项目',

    // Testimonials Section
    'testimonials.subtitle': '推荐',
    'testimonials.title': '客户反馈',
    'testimonials.description': '我的客户对与我合作以及我们共同取得的成果的评价。',
    'testimonials.trustedBy': '受创意品牌信赖',
    'testimonials.trustedByDesc': '我有幸与令人惊叹的品牌和创意机构合作。',

    // Contact Section
    'contact.subtitle': '联系',
    'contact.title1': '让我们',
    'contact.title2': '一起',
    'contact.title3': '创造',
    'contact.description': '准备将您的创意愿景变为现实？让我们讨论您的项目，一起创造令人惊叹的作品。',
    'contact.getInTouch': '取得联系',
    'contact.getInTouchDesc': '我总是很兴奋能够参与新的创意项目。',
    'contact.email': '邮箱',
    'contact.emailDesc': '给我发消息',
    'contact.phone': '电话',
    'contact.phoneDesc': '直接给我打电话',
    'contact.location': '位置',
    'contact.locationDesc': '位于瑞士',
    'contact.followMe': '关注我',
    'contact.sendMessage': '发送消息',
    'contact.name': '姓名',
    'contact.namePlaceholder': '您的姓名',
    'contact.emailPlaceholder': '您的邮箱@例子.com',
    'contact.subject': '主题',
    'contact.subjectPlaceholder': '项目主题',
    'contact.message': '消息',
    'contact.messagePlaceholder': '告诉我您的项目...',
    'contact.sendBtn': '发送消息',

    // Footer
    'footer.description': '专注于品牌识别和视觉叙事的创意设计师。创造真实的体验，连接品牌与其受众。',
    'footer.quickLinks': '快速链接',
    'footer.services': '服务',
    'footer.brandIdentity': '品牌识别',
    'footer.uiuxDesign': '平面设计',
    'footer.webDevelopment': '印刷设计',
    'footer.motionGraphics': '动态图形',
    'footer.madeWith': '制作于',
    'footer.inSwitzerland': '瑞士',
    'footer.allRights': '© 2024 Theo Blondel. 版权所有。'
  },
  ja: {
    // Navigation
    'nav.about': 'について',
    'nav.work': '作品',
    'nav.services': 'サービス',
    'nav.contact': 'お問い合わせ',
    'nav.letsTalk': 'お話しましょう',

    // Hero Section
    'hero.subtitle': 'クリエイティブデザイナー＆ブランドストラテジスト',
    'hero.greeting': 'こんにちは、私はテオ・ブロンデルです',
    'hero.title1': 'クリエイティブ',
    'hero.title2': 'デザイナー',
    'hero.title3': 'プロフェッショナル',
    'hero.description': 'ブランドアイデンティティとビジュアルデザインを専門としています。あなたのストーリーを語る本物のビジュアル体験と記憶に残るブランドアイデンティティを創造します。',
    'hero.contactMe': 'お問い合わせ',
    'hero.watchDemo': 'デモを見る',
    'hero.yearsExperience': '年の経験',
    'hero.projectsDelivered': 'プロジェクト完了',
    'hero.clientSatisfaction': 'クライアント満足度',
    'hero.clientsWorldwide': '世界中のクライアント',
    'hero.service1.title': 'ブランドアイデンティティ',
    'hero.service1.desc': 'ロゴデザインと完全なビジュアルアイデンティティシステム',
    'hero.service2.title': 'グラフィックデザイン',
    'hero.service2.desc': '印刷物とデジタルデザインソリューション',
    'hero.service3.title': 'マーケティングデザイン',
    'hero.service3.desc': 'クリエイティブキャンペーンとマーケティング素材',
    'hero.service4.title': 'モーショングラフィックス',
    'hero.service4.desc': 'アニメーションコンテンツとビジュアルストーリーテリング',

    // About Section
    'about.subtitle': '私について',
    'about.title1': '情熱的な',
    'about.title2': 'クリエイティブ',
    'about.title3': 'プロフェッショナル',
    'about.description1': '5年以上のクリエイティブデザイン経験を持ち、ブランドアイデンティティとビジュアルストーリーテリングを専門としています。私のアプローチは戦略的思考とクリエイティブな実行を組み合わせ、インパクトのあるデザインソリューションを提供します。',
    'about.description2': '本物のビジュアルコミュニケーションの力でブランドを変革し、オーディエンスとの意味のあるつながりを創造することを信じています。',
    'about.skill1.title': 'ブランドアイデンティティ',
    'about.skill1.desc': 'ロゴデザイン、ビジュアルアイデンティティシステム、ブランドガイドライン',
    'about.skill2.title': 'グラフィックデザイン',
    'about.skill2.desc': '印刷デザイン、デジタルグラフィックス、マーケティング素材',
    'about.skill3.title': 'モーショングラフィックス',
    'about.skill3.desc': 'アニメーション、ビデオ編集、ビジュアルエフェクト',
    'about.skill4.title': 'クリエイティブ戦略',
    'about.skill4.desc': 'ブランドポジショニング、クリエイティブディレクション、キャンペーン戦略',

    // Portfolio Section
    'portfolio.subtitle': '私の作品',
    'portfolio.title1': '注目の',
    'portfolio.title2': 'クリエイティブ',
    'portfolio.title3': 'プロジェクト',
    'portfolio.description': 'ブランドアイデンティティからマーケティングキャンペーンまで、私のクリエイティブプロジェクトの選択をご覧ください。',
    'portfolio.category.all': 'すべてのプロジェクト',
    'portfolio.category.webApp': 'デジタルデザイン',
    'portfolio.category.branding': 'ブランディング',
    'portfolio.category.mobile': 'モバイルデザイン',
    'portfolio.category.animation': 'アニメーション',
    'portfolio.category.audio': 'クリエイティブ体験',
    'portfolio.viewAllBehance': 'Behanceですべて見る',

    // Services Section
    'services.subtitle': 'サービス',
    'services.title': 'クリエイティブソリューション',
    'services.description': 'あなたのブランドが際立ち、オーディエンスとつながるための包括的なクリエイティブサービスを提供します。',
    'services.brandIdentity.title': 'ブランドアイデンティティ',
    'services.brandIdentity.desc': 'ロゴデザイン、ビジュアルガイドライン、ブランド戦略を含む完全なブランドアイデンティティシステム。',
    'services.uiux.title': 'グラフィックデザイン',
    'services.uiux.desc': 'マーケティング素材、出版物、キャンペーンのための印刷物とデジタルデザインソリューション。',
    'services.webDev.title': '印刷デザイン',
    'services.webDev.desc': 'パンフレット、ポスター、パッケージング、企業素材のためのプロフェッショナルな印刷デザイン。',
    'services.mobile.title': 'マーケティングデザイン',
    'services.mobile.desc': 'あなたのブランドを効果的に宣伝するためのクリエイティブマーケティング素材とキャンペーンデザイン。',
    'services.motion.title': 'モーショングラフィックス',
    'services.motion.desc': 'デジタルキャンペーンのためのアニメーションコンテンツ、ビデオ編集、モーショングラフィックス。',
    'services.creative.title': 'クリエイティブディレクション',
    'services.creative.desc': '包括的なブランドキャンペーンのための戦略的クリエイティブディレクションとアートディレクション。',
    'services.startProject': 'プロジェクトを開始',

    // Testimonials Section
    'testimonials.subtitle': 'お客様の声',
    'testimonials.title': 'クライアントフィードバック',
    'testimonials.description': '私との仕事について、そして私たちが一緒に達成した結果について、私のクライアントが言っていることです。',
    'testimonials.trustedBy': 'クリエイティブブランドに信頼されています',
    'testimonials.trustedByDesc': '素晴らしいブランドとクリエイティブエージェンシーと仕事をする特権を持っています。',

    // Contact Section
    'contact.subtitle': 'お問い合わせ',
    'contact.title1': '一緒に',
    'contact.title2': '何かを',
    'contact.title3': '創造しましょう',
    'contact.description': 'あなたのクリエイティブビジョンを実現する準備はできていますか？あなたのプロジェクトについて話し合い、一緒に素晴らしいものを創造しましょう。',
    'contact.getInTouch': 'お問い合わせ',
    'contact.getInTouchDesc': '新しいクリエイティブプロジェクトに取り組むことにいつも興奮しています。',
    'contact.email': 'メール',
    'contact.emailDesc': 'メッセージを送る',
    'contact.phone': '電話',
    'contact.phoneDesc': '直接お電話ください',
    'contact.location': '場所',
    'contact.locationDesc': 'スイスを拠点',
    'contact.followMe': 'フォローしてください',
    'contact.sendMessage': 'メッセージを送る',
    'contact.name': '名前',
    'contact.namePlaceholder': 'あなたの名前',
    'contact.emailPlaceholder': 'あなたのメール@例.com',
    'contact.subject': '件名',
    'contact.subjectPlaceholder': 'プロジェクトの件名',
    'contact.message': 'メッセージ',
    'contact.messagePlaceholder': 'あなたのプロジェクトについて教えてください...',
    'contact.sendBtn': 'メッセージを送信',

    // Footer
    'footer.description': 'ブランドアイデンティティとビジュアルストーリーテリングを専門とするクリエイティブデザイナー。ブランドとオーディエンスをつなぐ本物の体験を創造します。',
    'footer.quickLinks': 'クイックリンク',
    'footer.services': 'サービス',
    'footer.brandIdentity': 'ブランドアイデンティティ',
    'footer.uiuxDesign': 'グラフィックデザイン',
    'footer.webDevelopment': '印刷デザイン',
    'footer.motionGraphics': 'モーショングラフィックス',
    'footer.madeWith': '作られました',
    'footer.inSwitzerland': 'スイスで',
    'footer.allRights': '© 2024 テオ・ブロンデル. すべての権利予約済み。'
  },
  de: {
    // Navigation
    'nav.about': 'Über',
    'nav.work': 'Arbeiten',
    'nav.services': 'Dienstleistungen',
    'nav.contact': 'Kontakt',
    'nav.letsTalk': 'Sprechen wir',

    // Hero Section
    'hero.subtitle': 'Kreativer Designer & Markenstratege',
    'hero.greeting': 'Hallo, ich bin Theo Blondel',
    'hero.title1': 'Kreativer',
    'hero.title2': 'Designer',
    'hero.title3': 'Profi',
    'hero.description': 'Spezialisiert auf Markenidentität und visuelles Design. Ich schaffe authentische visuelle Erlebnisse und unvergessliche Markenidentitäten, die Ihre Geschichte erzählen.',
    'hero.contactMe': 'Kontaktieren Sie mich',
    'hero.watchDemo': 'Demo ansehen',
    'hero.yearsExperience': 'Jahre Erfahrung',
    'hero.projectsDelivered': 'Projekte abgeliefert',
    'hero.clientSatisfaction': 'Kundenzufriedenheit',
    'hero.clientsWorldwide': 'Kunden weltweit',
    'hero.service1.title': 'Markenidentität',
    'hero.service1.desc': 'Logo-Design und vollständige visuelle Identitätssysteme',
    'hero.service2.title': 'Grafikdesign',
    'hero.service2.desc': 'Print- und digitale Designlösungen',
    'hero.service3.title': 'Marketing-Design',
    'hero.service3.desc': 'Kreative Kampagnen und Marketingmaterialien',
    'hero.service4.title': 'Motion Graphics',
    'hero.service4.desc': 'Animierte Inhalte und visuelles Storytelling',

    // About Section
    'about.subtitle': 'Über mich',
    'about.title1': 'Leidenschaftlicher',
    'about.title2': 'Kreativer',
    'about.title3': 'Profi',
    'about.description1': 'Mit über 5 Jahren Erfahrung im kreativen Design spezialisiere ich mich auf Markenidentität und visuelles Storytelling. Mein Ansatz kombiniert strategisches Denken mit kreativer Umsetzung, um wirkungsvolle Designlösungen zu liefern.',
    'about.description2': 'Ich glaube an die Kraft authentischer visueller Kommunikation, um Marken zu transformieren und bedeutungsvolle Verbindungen mit dem Publikum zu schaffen.',
    'about.skill1.title': 'Markenidentität',
    'about.skill1.desc': 'Logo-Design, visuelle Identitätssysteme, Markenrichtlinien',
    'about.skill2.title': 'Grafikdesign',
    'about.skill2.desc': 'Print-Design, digitale Grafiken, Marketingmaterialien',
    'about.skill3.title': 'Motion Graphics',
    'about.skill3.desc': 'Animation, Videobearbeitung, visuelle Effekte',
    'about.skill4.title': 'Kreative Strategie',
    'about.skill4.desc': 'Markenpositionierung, kreative Leitung, Kampagnenstrategie',

    // Portfolio Section
    'portfolio.subtitle': 'Meine Arbeiten',
    'portfolio.title1': 'Ausgewählte',
    'portfolio.title2': 'Kreative',
    'portfolio.title3': 'Projekte',
    'portfolio.description': 'Entdecken Sie eine Auswahl meiner kreativen Projekte, von Markenidentitäten bis hin zu Marketingkampagnen.',
    'portfolio.category.all': 'Alle Projekte',
    'portfolio.category.webApp': 'Digitales Design',
    'portfolio.category.branding': 'Branding',
    'portfolio.category.mobile': 'Mobile Design',
    'portfolio.category.animation': 'Animation',
    'portfolio.category.audio': 'Kreative Erfahrung',
    'portfolio.viewAllBehance': 'Alle auf Behance ansehen',

    // Services Section
    'services.subtitle': 'Dienstleistungen',
    'services.title': 'Kreative Lösungen',
    'services.description': 'Ich biete umfassende kreative Dienstleistungen, um Ihrer Marke zu helfen, sich abzuheben und mit Ihrem Publikum zu verbinden.',
    'services.brandIdentity.title': 'Markenidentität',
    'services.brandIdentity.desc': 'Vollständige Markenidentitätssysteme einschließlich Logo-Design, visuelle Richtlinien und Markenstrategie.',
    'services.uiux.title': 'Grafikdesign',
    'services.uiux.desc': 'Print- und digitale Designlösungen für Marketingmaterialien, Publikationen und Kampagnen.',
    'services.webDev.title': 'Print-Design',
    'services.webDev.desc': 'Professionelles Print-Design für Broschüren, Poster, Verpackungen und Unternehmensmaterialien.',
    'services.mobile.title': 'Marketing-Design',
    'services.mobile.desc': 'Kreative Marketingmaterialien und Kampagnendesign zur effektiven Förderung Ihrer Marke.',
    'services.motion.title': 'Motion Graphics',
    'services.motion.desc': 'Animierte Inhalte, Videobearbeitung und Motion Graphics für digitale Kampagnen.',
    'services.creative.title': 'Kreative Leitung',
    'services.creative.desc': 'Strategische kreative Leitung und Art Direction für umfassende Markenkampagnen.',
    'services.startProject': 'Projekt starten',

    // Testimonials Section
    'testimonials.subtitle': 'Testimonials',
    'testimonials.title': 'Kundenfeedback',
    'testimonials.description': 'Was meine Kunden über die Zusammenarbeit mit mir und die Ergebnisse sagen, die wir gemeinsam erzielt haben.',
    'testimonials.trustedBy': 'Vertraut von kreativen Marken',
    'testimonials.trustedByDesc': 'Ich hatte das Privileg, mit erstaunlichen Marken und kreativen Agenturen zu arbeiten.',

    // Contact Section
    'contact.subtitle': 'Kontakt',
    'contact.title1': 'Lassen Sie uns',
    'contact.title2': 'gemeinsam',
    'contact.title3': 'schaffen',
    'contact.description': 'Bereit, Ihre kreative Vision zum Leben zu erwecken? Lassen Sie uns über Ihr Projekt sprechen und gemeinsam etwas Erstaunliches schaffen.',
    'contact.getInTouch': 'Kontakt aufnehmen',
    'contact.getInTouchDesc': 'Ich bin immer begeistert, an neuen kreativen Projekten zu arbeiten.',
    'contact.email': 'E-Mail',
    'contact.emailDesc': 'Senden Sie mir eine Nachricht',
    'contact.phone': 'Telefon',
    'contact.phoneDesc': 'Rufen Sie mich direkt an',
    'contact.location': 'Standort',
    'contact.locationDesc': 'Ansässig in der Schweiz',
    'contact.followMe': 'Folgen Sie mir',
    'contact.sendMessage': 'Nachricht senden',
    'contact.name': 'Name',
    'contact.namePlaceholder': 'Ihr Name',
    'contact.emailPlaceholder': 'ihre.email@beispiel.com',
    'contact.subject': 'Betreff',
    'contact.subjectPlaceholder': 'Projektbetreff',
    'contact.message': 'Nachricht',
    'contact.messagePlaceholder': 'Erzählen Sie mir von Ihrem Projekt...',
    'contact.sendBtn': 'Nachricht senden',

    // Footer
    'footer.description': 'Kreativer Designer spezialisiert auf Markenidentität und visuelles Storytelling. Schaffung authentischer Erlebnisse, die Marken mit ihrem Publikum verbinden.',
    'footer.quickLinks': 'Schnelle Links',
    'footer.services': 'Dienstleistungen',
    'footer.brandIdentity': 'Markenidentität',
    'footer.uiuxDesign': 'Grafikdesign',
    'footer.webDevelopment': 'Print-Design',
    'footer.motionGraphics': 'Motion Graphics',
    'footer.madeWith': 'Gemacht mit',
    'footer.inSwitzerland': 'in der Schweiz',
    'footer.allRights': '© 2024 Theo Blondel. Alle Rechte vorbehalten.'
  },
  it: {
    // Navigation
    'nav.about': 'Chi Sono',
    'nav.work': 'Lavori',
    'nav.services': 'Servizi',
    'nav.contact': 'Contatto',
    'nav.letsTalk': 'Parliamone',

    // Hero Section
    'hero.subtitle': 'Designer Creativo e Stratega del Brand',
    'hero.greeting': 'Ciao, sono Theo Blondel',
    'hero.title1': 'Designer',
    'hero.title2': 'Creativo',
    'hero.title3': 'Professionale',
    'hero.description': 'Specializzato in identità di brand e design visivo. Creo esperienze visive autentiche e identità di marca memorabili che raccontano la tua storia.',
    'hero.contactMe': 'Contattami',
    'hero.watchDemo': 'Guarda Demo',
    'hero.yearsExperience': 'Anni di Esperienza',
    'hero.projectsDelivered': 'Progetti Consegnati',
    'hero.clientSatisfaction': 'Soddisfazione Cliente',
    'hero.clientsWorldwide': 'Clienti nel Mondo',
    'hero.service1.title': 'Identità di Brand',
    'hero.service1.desc': 'Design di loghi e sistemi di identità visiva completi',
    'hero.service2.title': 'Design Grafico',
    'hero.service2.desc': 'Soluzioni di design stampato e digitale',
    'hero.service3.title': 'Design Marketing',
    'hero.service3.desc': 'Campagne creative e materiali di marketing',
    'hero.service4.title': 'Motion Graphics',
    'hero.service4.desc': 'Contenuti animati e storytelling visivo',

    // About Section
    'about.subtitle': 'Chi Sono',
    'about.title1': 'Creativo',
    'about.title2': 'Appassionato',
    'about.title3': 'Professionale',
    'about.description1': 'Con oltre 5 anni di esperienza nel design creativo, mi specializzo in identità di brand e storytelling visivo. Il mio approccio combina pensiero strategico ed esecuzione creativa per fornire soluzioni di design d\'impatto.',
    'about.description2': 'Credo nel potere della comunicazione visiva autentica per trasformare i brand e creare connessioni significative con il pubblico.',
    'about.skill1.title': 'Identità di Brand',
    'about.skill1.desc': 'Design di loghi, sistemi di identità visiva, linee guida del brand',
    'about.skill2.title': 'Design Grafico',
    'about.skill2.desc': 'Design stampato, grafica digitale, materiali di marketing',
    'about.skill3.title': 'Motion Graphics',
    'about.skill3.desc': 'Animazione, editing video, effetti visivi',
    'about.skill4.title': 'Strategia Creativa',
    'about.skill4.desc': 'Posizionamento del brand, direzione creativa, strategia di campagna',

    // Portfolio Section
    'portfolio.subtitle': 'I Miei Lavori',
    'portfolio.title1': 'Progetti',
    'portfolio.title2': 'Creativi',
    'portfolio.title3': 'Selezionati',
    'portfolio.description': 'Scopri una selezione dei miei progetti creativi, dalle identità di brand alle campagne di marketing.',
    'portfolio.category.all': 'Tutti i Progetti',
    'portfolio.category.webApp': 'Design Digitale',
    'portfolio.category.branding': 'Branding',
    'portfolio.category.mobile': 'Design Mobile',
    'portfolio.category.animation': 'Animazione',
    'portfolio.category.audio': 'Esperienza Creativa',
    'portfolio.viewAllBehance': 'Vedi Tutto su Behance',

    // Services Section
    'services.subtitle': 'Servizi',
    'services.title': 'Soluzioni Creative',
    'services.description': 'Offro servizi creativi completi per aiutare il tuo brand a distinguersi e connettersi con il tuo pubblico.',
    'services.brandIdentity.title': 'Identità di Brand',
    'services.brandIdentity.desc': 'Sistemi completi di identità di brand inclusi design del logo, linee guida visive e strategia del brand.',
    'services.uiux.title': 'Design Grafico',
    'services.uiux.desc': 'Soluzioni di design stampato e digitale per materiali di marketing, pubblicazioni e campagne.',
    'services.webDev.title': 'Design Stampato',
    'services.webDev.desc': 'Design stampato professionale per brochure, poster, packaging e materiali aziendali.',
    'services.mobile.title': 'Design Marketing',
    'services.mobile.desc': 'Materiali di marketing creativi e design di campagne per promuovere efficacemente il tuo brand.',
    'services.motion.title': 'Motion Graphics',
    'services.motion.desc': 'Contenuti animati, editing video e motion graphics per campagne digitali.',
    'services.creative.title': 'Direzione Creativa',
    'services.creative.desc': 'Direzione creativa strategica e art direction per campagne di brand complete.',
    'services.startProject': 'Inizia un Progetto',

    // Testimonials Section
    'testimonials.subtitle': 'Testimonianze',
    'testimonials.title': 'Feedback dei Clienti',
    'testimonials.description': 'Cosa dicono i miei clienti del lavorare con me e dei risultati che abbiamo ottenuto insieme.',
    'testimonials.trustedBy': 'Fidato da Brand Creativi',
    'testimonials.trustedByDesc': 'Ho avuto il privilegio di lavorare con brand e agenzie creative straordinari.',

    // Contact Section
    'contact.subtitle': 'Contatto',
    'contact.title1': 'Creiamo',
    'contact.title2': 'Qualcosa',
    'contact.title3': 'Insieme',
    'contact.description': 'Pronto a dare vita alla tua visione creativa? Parliamo del tuo progetto e creiamo qualcosa di straordinario insieme.',
    'contact.getInTouch': 'Mettiamoci in Contatto',
    'contact.getInTouchDesc': 'Sono sempre entusiasta di lavorare su nuovi progetti creativi.',
    'contact.email': 'Email',
    'contact.emailDesc': 'Inviami un messaggio',
    'contact.phone': 'Telefono',
    'contact.phoneDesc': 'Chiamami direttamente',
    'contact.location': 'Posizione',
    'contact.locationDesc': 'Con sede in Svizzera',
    'contact.followMe': 'Seguimi',
    'contact.sendMessage': 'Invia un Messaggio',
    'contact.name': 'Nome',
    'contact.namePlaceholder': 'Il tuo nome',
    'contact.emailPlaceholder': 'tua.email@esempio.com',
    'contact.subject': 'Oggetto',
    'contact.subjectPlaceholder': 'Oggetto del progetto',
    'contact.message': 'Messaggio',
    'contact.messagePlaceholder': 'Parlami del tuo progetto...',
    'contact.sendBtn': 'Invia Messaggio',

    // Footer
    'footer.description': 'Designer creativo specializzato in identità di brand e storytelling visivo. Creazione di esperienze autentiche che connettono i brand con il loro pubblico.',
    'footer.quickLinks': 'Link Rapidi',
    'footer.services': 'Servizi',
    'footer.brandIdentity': 'Identità di Brand',
    'footer.uiuxDesign': 'Design Grafico',
    'footer.webDevelopment': 'Design Stampato',
    'footer.motionGraphics': 'Motion Graphics',
    'footer.madeWith': 'Fatto con',
    'footer.inSwitzerland': 'in Svizzera',
    'footer.allRights': '© 2024 Theo Blondel. Tutti i diritti riservati.'
  },
  pt: {
    // Navigation
    'nav.about': 'Sobre',
    'nav.work': 'Trabalhos',
    'nav.services': 'Serviços',
    'nav.contact': 'Contato',
    'nav.letsTalk': 'Vamos Conversar',

    // Hero Section
    'hero.subtitle': 'Designer Criativo e Estrategista de Marca',
    'hero.greeting': 'Olá, eu sou Theo Blondel',
    'hero.title1': 'Designer',
    'hero.title2': 'Criativo',
    'hero.title3': 'Profissional',
    'hero.description': 'Especializado em identidade de marca e design visual. Crio experiências visuais autênticas e identidades de marca memoráveis que contam sua história.',
    'hero.contactMe': 'Entre em Contato',
    'hero.watchDemo': 'Ver Demo',
    'hero.yearsExperience': 'Anos de Experiência',
    'hero.projectsDelivered': 'Projetos Entregues',
    'hero.clientSatisfaction': 'Satisfação do Cliente',
    'hero.clientsWorldwide': 'Clientes Mundiais',
    'hero.service1.title': 'Identidade de Marca',
    'hero.service1.desc': 'Design de logos e sistemas completos de identidade visual',
    'hero.service2.title': 'Design Gráfico',
    'hero.service2.desc': 'Soluções de design impresso e digital',
    'hero.service3.title': 'Design de Marketing',
    'hero.service3.desc': 'Campanhas criativas e materiais de marketing',
    'hero.service4.title': 'Motion Graphics',
    'hero.service4.desc': 'Conteúdo animado e storytelling visual',

    // About Section
    'about.subtitle': 'Sobre Mim',
    'about.title1': 'Criativo',
    'about.title2': 'Apaixonado',
    'about.title3': 'Profissional',
    'about.description1': 'Com mais de 5 anos de experiência em design criativo, me especializo em identidade de marca e storytelling visual. Minha abordagem combina pensamento estratégico com execução criativa para entregar soluções de design impactantes.',
    'about.description2': 'Acredito no poder da comunicação visual autêntica para transformar marcas e criar conexões significativas com o público.',
    'about.skill1.title': 'Identidade de Marca',
    'about.skill1.desc': 'Design de logos, sistemas de identidade visual, diretrizes de marca',
    'about.skill2.title': 'Design Gráfico',
    'about.skill2.desc': 'Design impresso, gráficos digitais, materiais de marketing',
    'about.skill3.title': 'Motion Graphics',
    'about.skill3.desc': 'Animação, edição de vídeo, efeitos visuais',
    'about.skill4.title': 'Estratégia Criativa',
    'about.skill4.desc': 'Posicionamento de marca, direção criativa, estratégia de campanha',

    // Portfolio Section
    'portfolio.subtitle': 'Meus Trabalhos',
    'portfolio.title1': 'Projetos',
    'portfolio.title2': 'Criativos',
    'portfolio.title3': 'Selecionados',
    'portfolio.description': 'Descubra uma seleção dos meus projetos criativos, desde identidades de marca até campanhas de marketing.',
    'portfolio.category.all': 'Todos os Projetos',
    'portfolio.category.webApp': 'Design Digital',
    'portfolio.category.branding': 'Branding',
    'portfolio.category.mobile': 'Design Mobile',
    'portfolio.category.animation': 'Animação',
    'portfolio.category.audio': 'Experiência Criativa',
    'portfolio.viewAllBehance': 'Ver Tudo no Behance',

    // Services Section
    'services.subtitle': 'Serviços',
    'services.title': 'Soluções Criativas',
    'services.description': 'Ofereço serviços criativos abrangentes para ajudar sua marca a se destacar e se conectar com seu público.',
    'services.brandIdentity.title': 'Identidade de Marca',
    'services.brandIdentity.desc': 'Sistemas completos de identidade de marca incluindo design de logo, diretrizes visuais e estratégia de marca.',
    'services.uiux.title': 'Design Gráfico',
    'services.uiux.desc': 'Soluções de design impresso e digital para materiais de marketing, publicações e campanhas.',
    'services.webDev.title': 'Design Impresso',
    'services.webDev.desc': 'Design impresso profissional para folhetos, cartazes, embalagens e materiais corporativos.',
    'services.mobile.title': 'Design de Marketing',
    'services.mobile.desc': 'Materiais de marketing criativos e design de campanhas para promover sua marca efetivamente.',
    'services.motion.title': 'Motion Graphics',
    'services.motion.desc': 'Conteúdo animado, edição de vídeo e motion graphics para campanhas digitais.',
    'services.creative.title': 'Direção Criativa',
    'services.creative.desc': 'Direção criativa estratégica e direção de arte para campanhas de marca abrangentes.',
    'services.startProject': 'Iniciar um Projeto',

    // Testimonials Section
    'testimonials.subtitle': 'Depoimentos',
    'testimonials.title': 'Feedback dos Clientes',
    'testimonials.description': 'O que meus clientes dizem sobre trabalhar comigo e os resultados que alcançamos juntos.',
    'testimonials.trustedBy': 'Confiado por Marcas Criativas',
    'testimonials.trustedByDesc': 'Tive o privilégio de trabalhar com marcas e agências criativas incríveis.',

    // Contact Section
    'contact.subtitle': 'Contato',
    'contact.title1': 'Vamos',
    'contact.title2': 'Criar',
    'contact.title3': 'Juntos',
    'contact.description': 'Pronto para dar vida à sua visão criativa? Vamos discutir seu projeto e criar algo incrível juntos.',
    'contact.getInTouch': 'Entre em Contato',
    'contact.getInTouchDesc': 'Estou sempre animado para trabalhar em novos projetos criativos.',
    'contact.email': 'Email',
    'contact.emailDesc': 'Envie-me uma mensagem',
    'contact.phone': 'Telefone',
    'contact.phoneDesc': 'Ligue diretamente',
    'contact.location': 'Localização',
    'contact.locationDesc': 'Baseado na Suíça',
    'contact.followMe': 'Siga-me',
    'contact.sendMessage': 'Enviar uma Mensagem',
    'contact.name': 'Nome',
    'contact.namePlaceholder': 'Seu nome',
    'contact.emailPlaceholder': 'seu.email@exemplo.com',
    'contact.subject': 'Assunto',
    'contact.subjectPlaceholder': 'Assunto do projeto',
    'contact.message': 'Mensagem',
    'contact.messagePlaceholder': 'Conte-me sobre seu projeto...',
    'contact.sendBtn': 'Enviar Mensagem',

    // Footer
    'footer.description': 'Designer criativo especializado em identidade de marca e storytelling visual. Criando experiências autênticas que conectam marcas com seu público.',
    'footer.quickLinks': 'Links Rápidos',
    'footer.services': 'Serviços',
    'footer.brandIdentity': 'Identidade de Marca',
    'footer.uiuxDesign': 'Design Gráfico',
    'footer.webDevelopment': 'Design Impresso',
    'footer.motionGraphics': 'Motion Graphics',
    'footer.madeWith': 'Feito com',
    'footer.inSwitzerland': 'na Suíça',
    'footer.allRights': '© 2024 Theo Blondel. Todos os direitos reservados.'
  },
  sq: {
    // Navigation
    'nav.about': 'Rreth',
    'nav.work': 'Punët',
    'nav.services': 'Shërbimet',
    'nav.contact': 'Kontakti',
    'nav.letsTalk': 'Le të Flasim',

    // Hero Section
    'hero.subtitle': 'Dizajner Kreativ dhe Strategjist i Markës',
    'hero.greeting': 'Përshëndetje, unë jam Theo Blondel',
    'hero.title1': 'Dizajner',
    'hero.title2': 'Kreativ',
    'hero.title3': 'Profesional',
    'hero.description': 'I specializuar në identitetin e markës dhe dizajnin vizual. Krijoj përvojë vizuale autentike dhe identitete të markës të paharrueshme që tregojnë historinë tuaj.',
    'hero.contactMe': 'Më Kontaktoni',
    'hero.watchDemo': 'Shiko Demo',
    'hero.yearsExperience': 'Vite Përvojë',
    'hero.projectsDelivered': 'Projekte të Dorëzuara',
    'hero.clientSatisfaction': 'Kënaqësia e Klientit',
    'hero.clientsWorldwide': 'Klientë në Mbarë Botën',
    'hero.service1.title': 'Identiteti i Markës',
    'hero.service1.desc': 'Dizajni i logos dhe sistemet e plota të identitetit vizual',
    'hero.service2.title': 'Dizajni Grafik',
    'hero.service2.desc': 'Zgjidhje dizajni të printuar dhe dixhital',
    'hero.service3.title': 'Dizajni i Marketingut',
    'hero.service3.desc': 'Fushata kreative dhe materiale marketingu',
    'hero.service4.title': 'Motion Graphics',
    'hero.service4.desc': 'Përmbajtje e animuar dhe tregim vizual',

    // About Section
    'about.subtitle': 'Rreth Meje',
    'about.title1': 'Kreativ',
    'about.title2': 'i Pasionuar',
    'about.title3': 'Profesional',
    'about.description1': 'Me mbi 5 vjet përvojë në dizajnin kreativ, specializohem në identitetin e markës dhe tregimet vizuale. Qasja ime kombinon mendimin strategjik me ekzekutimin kreativ për të ofruar zgjidhje dizajni me ndikim.',
    'about.description2': 'Besoj në fuqinë e komunikimit vizual autentik për të transformuar markat dhe për të krijuar lidhje kuptimplota me audiencën.',
    'about.skill1.title': 'Identiteti i Markës',
    'about.skill1.desc': 'Dizajni i logos, sistemet e identitetit vizual, udhëzimet e markës',
    'about.skill2.title': 'Dizajni Grafik',
    'about.skill2.desc': 'Dizajni i printuar, grafikë dixhitale, materiale marketingu',
    'about.skill3.title': 'Motion Graphics',
    'about.skill3.desc': 'Animacion, editim videosh, efekte vizuale',
    'about.skill4.title': 'Strategjia Kreative',
    'about.skill4.desc': 'Pozicionimi i markës, drejtimi kreativ, strategjia e fushatës',

    // Portfolio Section
    'portfolio.subtitle': 'Punët e Mia',
    'portfolio.title1': 'Projekte',
    'portfolio.title2': 'Kreative',
    'portfolio.title3': 'të Zgjedhura',
    'portfolio.description': 'Zbuloni një përzgjedhje të projekteve të mia kreative, nga identitetet e markës deri te fushatat e marketingut.',
    'portfolio.category.all': 'Të Gjitha Projektet',
    'portfolio.category.webApp': 'Dizajni Dixhital',
    'portfolio.category.branding': 'Branding',
    'portfolio.category.mobile': 'Dizajni Mobile',
    'portfolio.category.animation': 'Animacion',
    'portfolio.category.audio': 'Përvojë Kreative',
    'portfolio.viewAllBehance': 'Shiko të Gjitha në Behance',

    // Services Section
    'services.subtitle': 'Shërbimet',
    'services.title': 'Zgjidhje Kreative',
    'services.description': 'Ofroj shërbime kreative gjithëpërfshirëse për të ndihmuar markën tuaj të dallohet dhe të lidhet me audiencën tuaj.',
    'services.brandIdentity.title': 'Identiteti i Markës',
    'services.brandIdentity.desc': 'Sisteme të plota identiteti marke duke përfshirë dizajnin e logos, udhëzimet vizuale dhe strategjinë e markës.',
    'services.uiux.title': 'Dizajni Grafik',
    'services.uiux.desc': 'Zgjidhje dizajni të printuar dhe dixhital për materiale marketingu, publikime dhe fushata.',
    'services.webDev.title': 'Dizajni i Printuar',
    'services.webDev.desc': 'Dizajn profesional i printuar për broshura, postera, ambalazhe dhe materiale korporative.',
    'services.mobile.title': 'Dizajni i Marketingut',
    'services.mobile.desc': 'Materiale kreative marketingu dhe dizajn fushatash për të promovuar markën tuaj në mënyrë efektive.',
    'services.motion.title': 'Motion Graphics',
    'services.motion.desc': 'Përmbajtje e animuar, editim videosh dhe motion graphics për fushata dixhitale.',
    'services.creative.title': 'Drejtimi Kreativ',
    'services.creative.desc': 'Drejtim strategjik kreativ dhe drejtim artistik për fushata të plota të markës.',
    'services.startProject': 'Fillo një Projekt',

    // Testimonials Section
    'testimonials.subtitle': 'Dëshmi',
    'testimonials.title': 'Reagimet e Klientëve',
    'testimonials.description': 'Çfarë thonë klientët e mi për punën me mua dhe rezultatet që kemi arritur së bashku.',
    'testimonials.trustedBy': 'I Besuar nga Marka Kreative',
    'testimonials.trustedByDesc': 'Kam pasur privilegjin të punoj me marka dhe agjenci kreative të mahnitshme.',

    // Contact Section
    'contact.subtitle': 'Kontakti',
    'contact.title1': 'Le të',
    'contact.title2': 'Krijojmë',
    'contact.title3': 'Së Bashku',
    'contact.description': 'Gati të jepni jetë vizionit tuaj kreativ? Le të diskutojmë projektin tuaj dhe të krijojmë diçka të mahnitshme së bashku.',
    'contact.getInTouch': 'Kontaktoni',
    'contact.getInTouchDesc': 'Jam gjithmonë i emocionuar të punoj në projekte të reja kreative.',
    'contact.email': 'Email',
    'contact.emailDesc': 'Më dërgoni një mesazh',
    'contact.phone': 'Telefoni',
    'contact.phoneDesc': 'Më telefononi direkt',
    'contact.location': 'Vendndodhja',
    'contact.locationDesc': 'Me bazë në Zvicër',
    'contact.followMe': 'Më Ndiqni',
    'contact.sendMessage': 'Dërgo një Mesazh',
    'contact.name': 'Emri',
    'contact.namePlaceholder': 'Emri juaj',
    'contact.emailPlaceholder': 'email.juaj@shembull.com',
    'contact.subject': 'Tema',
    'contact.subjectPlaceholder': 'Tema e projektit',
    'contact.message': 'Mesazhi',
    'contact.messagePlaceholder': 'Më tregoni për projektin tuaj...',
    'contact.sendBtn': 'Dërgo Mesazhin',

    // Footer
    'footer.description': 'Dizajner kreativ i specializuar në identitetin e markës dhe tregimet vizuale. Krijimi i përvojave autentike që lidhin markat me audiencën e tyre.',
    'footer.quickLinks': 'Lidhje të Shpejta',
    'footer.services': 'Shërbimet',
    'footer.brandIdentity': 'Identiteti i Markës',
    'footer.uiuxDesign': 'Dizajni Grafik',
    'footer.webDevelopment': 'Dizajni i Printuar',
    'footer.motionGraphics': 'Motion Graphics',
    'footer.madeWith': 'Bërë me',
    'footer.inSwitzerland': 'në Zvicër',
    'footer.allRights': '© 2024 Theo Blondel. Të gjitha të drejtat e rezervuara.'
  }
};

export function AppProvider({ children }: { children: ReactNode }) {
  const [theme, setTheme] = useState<Theme>('light');
  const [language, setLanguage] = useState<Language>('fr');

  useEffect(() => {
    const savedTheme = localStorage.getItem('theme') as Theme;
    const savedLanguage = localStorage.getItem('language') as Language;
    
    if (savedTheme) {
      setTheme(savedTheme);
    }
    if (savedLanguage) {
      setLanguage(savedLanguage);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('theme', theme);
    if (theme === 'dark') {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [theme]);

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const toggleTheme = () => {
    setTheme(prev => prev === 'light' ? 'dark' : 'light');
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <AppContext.Provider value={{
      theme,
      language,
      toggleTheme,
      setLanguage,
      t
    }}>
      {children}
    </AppContext.Provider>
  );
}

export function useApp() {
  const context = useContext(AppContext);
  if (context === undefined) {
    throw new Error('useApp must be used within an AppProvider');
  }
  return context;
}